### ISSUE TITLE
"Cursor position outside buffer" error on large refactors

### ISSUE THREAD

**Issue by teddylear** [ThePrimeagen/refactoring.nvim#102]
As noted by [this code](https://github.com/ThePrimeagen/refactoring.nvim/blob/master/lua/refactoring/tasks/apply_text_edits.lua#L38-L45) we are having an issue with cursor position after the refactor takes place on the typescript switch statement test for extract function. This appears to be a bug in vim because it is not honoring the cursor position with the multiple edits that have taken place, and is throwing the cursor out of bounds of the buffer. Creating this to track on this repo, will link neovim issue as well.

**Comment by teddylear** [comment]
Made neovim ticket for issue: https://github.com/neovim/neovim/issues/15951

**Comment by ThePrimeagen** [comment]
@teddylear we should revisit this as the upstream ticket has been resolved

**Comment by teddylear** [comment]
Let me see if this is still an issue (I think it's been fixed upstream). Right now the main issue with moving cursor post refactor comes from extract func (the rest should work just find).  Extract func we usually start at 0, so the cursor always ends at 0. We could move it to the first non-space character in the start row, but then we would have to traverse the text there.

**Comment by teddylear** [comment]
Removed the bandaid put in for this, tests are passing for now so we should be good.
