### ISSUE TITLE
Use new vim.ui.input instead of vim.fn.input

### ISSUE THREAD

**Issue by IndianBoy42** [ThePrimeagen/refactoring.nvim#120]
`vim.ui.input` is a [newly merged](https://github.com/neovim/neovim/pull/15959) lua function for taking user text input. It is used by default in `vim.lsp.buf.rename()`. The advantage is it is 'overridable' with a custom lua function.
The API is not exactly the same, you must provide an `on_confirm` callback to receive the user input.
But this API allows for more flexibility, like implementing it using popup windows etc.

**Comment by ThePrimeagen** [comment]
Yaya!  Hey, feel free to open a PR, if not.  I am sure that at some point I will take a look at this.  It is not very high up on the priority list as I want to make extract * better.  * being extract anything (I want to be able to extract code to the function, another function, into class method, into another function in another file, etc etc.  So until I have made the most badass extraction code possible, I wont be doing any of these :)

**Comment by IndianBoy42** [comment]
Lets continue the discussion in #124. the difference in API of `ui.input` and `fn.input` will need changes to the Pipeline 'class'
