### ISSUE TITLE
Cannot extract code from global scope to function (Python)

### ISSUE THREAD

**Issue by thetic** [ThePrimeagen/refactoring.nvim#123]
Select the following in visual mode:

```python
print("o hai")
print("o hai")
print("o hai")
print("o hai")
```

Invoke `Extract Function`.

## Expected Behavior

prompt for name (eg foo) and edit code:

```python
def foo():
    print("o hai")
    print("o hai")
    print("o hai")
    print("o hai")


foo()
```

## Actual Behavior

`E5108: Error executing lua ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...start/refactoring.nvim/lua/refactoring/pipeline/ini
t.lua:61: Scope is nil`

**Comment by ThePrimeagen** [comment]
Python is really hard to make it right and no one is currently working on python actively that I know of.  I am going to put my thinking hat on here soon and start doing best effort indenting, but that is hard.  Python on the other hand is really hard since white space is significant.

**Comment by thetic** [comment]
totally fair. nothing urgent. I just thought it was worth capturing.

**Comment by ThePrimeagen** [comment]
this is really good, thanks for reporting.  Always appreciate the helping hand.

**Comment by teddylear** [comment]
@thetic Added support for this with the above PR and the test case you listed (though formatting is off but Prime is working on something to fix that across the board). Lmk if this resolves issue, thanks!.

**Comment by thetic** [comment]
Now I get this error:
```
E5108: Error executing lua ...ker/start/refactoring.nvim/lua/refactoring/get_input.lua:8: attempt to call field 'input' (a nil value)
```

**Comment by teddylear** [comment]
Not sure how you're getting that, are you on nightly neovim?  We only test on nightly, I can update docs to reflect that

**Comment by teddylear** [comment]
Also do you have `plenary` and `nvim-treesitter` plugins?

**Comment by thetic** [comment]
Ah, I wasn't on nighty. Thanks!
