### ISSUE TITLE
Feature request: Remove "all breadcrumbs" once finished

### ISSUE THREAD

**Issue by eecopa** [ThePrimeagen/refactoring.nvim#127]
First I want to say how awesome this tool is! That being said, after seeing this new feature https://www.youtube.com/watch?v=SDPei-mk13w
I thought it might be awesome to have a "remove all breadcrumbs" (remove print statements generated by the feature). 

## Why? 
I worked on multiple big projects that have print statements that should stay in there, and this would allow for easy deletion of the tool-generated prints without messing with other logs.

**Comment by ThePrimeagen** [comment]
ABSOLUTELY!  

So here is my general idea

```
code.print(msg) .. code.comment("__AUTO_GENERATED__")
```

then there could be a "cleanup" command that would be ran on the specific file and delete whatever line is a `print` line + has `__AUTO_GENERATE__` 

On top of that I need to get some customized stringification!

**Comment by teddylear** [comment]
@eecopa @ThePrimeagen I think this is taken care of by @pranavrao145 PR that just got merged. Let me know if this is good to close.

**Comment by ThePrimeagen** [comment]
If it's not taken care of, sorry about my absence for the last month, then this would be awesome.

Thanks so much for your contribution

**Comment by teddylear** [comment]
Closing as I think this has been resolved with debug cleanup
