### ISSUE TITLE
Attempt to call field 'input' (a nil value)

### ISSUE THREAD

**Issue by kavinvalli** [ThePrimeagen/refactoring.nvim#130]
I get this error when trying to run a command
```
E5108: Error executing lua ...ker/start/refactoring.nvim/lua/refactoring/get_input.lua:8: attempt to call field 'input' (a nil value)
```

**Comment by kavinvalli** [comment]
I tried to read the source code. Apparently, the get_input file has an `input` variable which uses plenary. I do have it installed though

**Comment by christofferaakre** [comment]
I get a similar error when trying to run 
`:lua require('refactoring').refactor('Extract Function')`:
```
E5108: Error executing lua ...ki/.vim/plugged/plenary.nvim/lua/plen
ary/async/async.lua:14: The coroutine failed with this message: ...
/.vim/plugged/refactoring.nvim/lua/refactoring/query.lua:30: attemp
t to index local 'parser' (a nil value)
stack traceback:
        [C]: in function 'error'
        ...ki/.vim/plugged/plenary.nvim/lua/plenary/async/async.lua
:14: in function 'callback_or_next'
        ...ki/.vim/plugged/plenary.nvim/lua/plenary/async/async.lua
:40: in function 'step'
        ...ki/.vim/plugged/plenary.nvim/lua/plenary/async/async.lua
:43: in function 'execute'
        ...ki/.vim/plugged/plenary.nvim/lua/plenary/async/async.lua
:113: in function <...ki/.vim/plugged/plenary.nvim/lua/plenary/asyn
c/async.lua:112>
        ...ugged/refactoring.nvim/lua/refactoring/pipeline/init.lua
:70: in function 'run'
        ...lugged/refactoring.nvim/lua/refactoring/refactor/106.lua
:154: in function <...lugged/refactoring.nvim/lua/refactoring/refac
tor/106.lua:146>
        ...i/.vim/plugged/refactoring.nvim/lua/refactoring/init.lua
:23: in function 'refactor'
        [string ":lua"]:1: in main chunk
```

**Comment by mcritchlow** [comment]
Ran into this too while trying to kick at adding Ruby language support. 

I suspect this got introduced here https://github.com/ThePrimeagen/refactoring.nvim/commit/3ea5c19072e3e10ad7ce2a69a9a8431e143c1ec5 but I'm still very new to all this

**Comment by teddylear** [comment]
Are people seeing this error when running nightly neovim? We need to update docs to clarify that this plugin only works on nightly, with nightly I'm not seeing this error.

**Comment by pranavrao145** [comment]
Yes, the plugin only works on nightly for me as well. Now that it specifies that nightly is necessary in the README, I think we should be okay to close this issue.

**Comment by kavinvalli** [comment]
> Are people seeing this error when running nightly neovim? We need to update docs to clarify that this plugin only works on nightly, with nightly I'm not seeing this error.

@teddylear Thanks for clarifying. It wasn't in the readme before so didn't know.
