### ISSUE TITLE
doesn't check if inside comment

### ISSUE THREAD

**Issue by max397574** [ThePrimeagen/refactoring.nvim#200]
I tried to extract a function in c++
As far as I can tell everything worked, except that the function got placed inside of a comment which was directly above the function:
![Screenshot 2022-01-03 at 18 47 57](https://user-images.githubusercontent.com/81827001/147962545-bd7cd269-e7bd-4a04-b370-3e2dcf60b0dd.png)

`:lua require('refactoring').refactor('Extract Function')`

![Screenshot 2022-01-03 at 18 48 17](https://user-images.githubusercontent.com/81827001/147962578-3859eda0-b498-443e-a5b0-0c9f605fc8a1.png)

**Comment by teddylear** [comment]
@max397574 I think this might be a more general problem with the plugin regarding refactoring around comments, let me look into this.

**Comment by vuki656** [comment]
I'm also experiencing this with lua so it's likely not a CPP-specific issue.

**Comment by teddylear** [comment]
@vuki656 Put in a fix for all but lua and python. 

@max397574 working on trying get lua and python working next, they're a little more complex.

**Comment by teddylear** [comment]
@max397574 added support for lua/python, let me know if there are still issues

**Comment by max397574** [comment]
I don't have any
You can close this issue if you also don't have any
