### ISSUE TITLE
Comparison with LucHermitte/vim-refactor

### ISSUE THREAD

**Issue by TamaMcGlinn** [ThePrimeagen/refactoring.nvim#21]
Hi. I just spotted [LucHermitte/vim-refactor](https://github.com/LucHermitte/vim-refactor) and wanted to be sure you weren't doing any duplicate work. He claims to have language-agnostic function & variable extraction working [(doesn't work for me though)](https://github.com/LucHermitte/vim-refactor/issues/1), so I guess he is using the same LSP-based approach as you.

**Comment by ThePrimeagen** [comment]
I have two reasons why I'm doing this.

1. Really learning the book refactoring.
2. Really learning tree sitter and lsp.

At the end of the day there isn't a great solution out there yet. I'll go review his repo and see how far he's made it, but I'll probably continue on doing work regardless of how far he's gone.

**Comment by ThePrimeagen** [comment]
After taking a moment to look at the repo.  We will shortly pass in supported refactors and languages.

I plan on implementing several more refactors.

**Comment by LucHermitte** [comment]
Hi.

In vim-refactor, I don' rely on LSP as this protocol did not exist by the time I've started working on vim-refactor. Instead I use ctags to find local variables, parameters, and so on, and then I try to take care of the extraction on vim side. Unfortunately ctags is quite bad to find everything I need and the result isn't very good. 

LSP could have been nice however this protocol doesn't offer any tool to inspect source code and do this at vim level. Instead it has to be done in each LSP server, IIRC. For C and C++ I may have a look in a very distant future at what I could find with libclang (through [another plugin of mine](https://github.com/LucHermitte/vim-clang/tree/V2Upgrade)).

Then as you have seen, vim-refactor has a few customization points to apply any active naming policy through [lh-style](https://lh-style.readthedocs.io/en/latest/naming.html#options-to-tune-the-naming-policy), and it uses mu-template in other places to generate code. Given C++ (my everyday programming language) specificities, I do some other stuff regarding parameter passing, variable/type declaration...
