### ISSUE TITLE
Adding java support for print_var

### ISSUE THREAD

**Issue by shawnyu5** [ThePrimeagen/refactoring.nvim#212]
Calling print_var in a java file causes plenary to error out. Having Java support in the plugin would be really cool.

**Comment by pranavrao145** [comment]
I will work on this when I get the chance :+1:

**Comment by pranavrao145** [comment]
@shawnyu5 support for Java is added in #230 - take a look and let me know what you think!

**Comment by shawnyu5** [comment]
Awesome, I'll play around with it. Thank You!
