### ISSUE TITLE
Error when treesitter is not setup 

### ISSUE THREAD

**Issue by zemzale** [ThePrimeagen/refactoring.nvim#216]
# Problem
I was trying out the plugin with a simple function extraction. The action ended with an error 
```
E5108: Error executing lua ...ig/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: .../nvim/plugged/refactor
ing.nvim/lua/refactoring/query.lua:22: attempt to index local 'parser' (a nil value)
```

I figured out that I just hadn't installed the treesitters parser. Installing it fixed the problem. 

# Solution 

Maybe it's possible to print some sort of warning if the parser is not available. The place where this all happens is here.

https://github.com/ThePrimeagen/refactoring.nvim/blob/de00774f2d5fbfd6578a32d001adacf9ed835e77/lua/refactoring/query.lua#L21

If so what would be the correct way of doing that? First time jumping into neovim plugins or lua for that matter.

**Comment by pranavrao145** [comment]
@zemzale yep is where we attempt to get the parser - technically Treesitter (and its parsers) are a requirement for the plugin, but if you would like to make a PR to print this warning message and make it more obvious for users, we'd be happy to accept it.

**Comment by teddylear** [comment]
@zemzale If you check if the parser is nil then throw error if that's the case you should be good. Not sure how easy it would be to add a test for that... but if you make a PR for what I mentioned I'd be down to merge

**Comment by pranavrao145** [comment]
@zemzale now that #225 is merged, lmk if we're good to close this issue.

**Comment by zemzale** [comment]
@pranavrao145 Yeah I think this can be closed

**Comment by pranavrao145** [comment]
Awesome, I'll close this then - thanks for the contributions!
