### ISSUE TITLE
Go: Setting return type for struct functions doesn't work

### ISSUE THREAD

**Issue by zemzale** [ThePrimeagen/refactoring.nvim#220]
Basically, as the title says. 

When I try to refactor something like this
```go
type Slicer struct {                                                        
    s []int 
}                            
                  
func (s Slicer) Sum() int {
    sum := 0         
    for _, val := range s.s {
        sum += i      
    }
                             
    return sum         
}    
  ```
  I get prompted for the function name and the return type, but it doesn't apply it
  ```go
  type Slicer struct {
      s []int
  }
  
  func (s Slicer) sumSlice() INPUT_RETURN_TYPE {
      sum := 0
      for _, val := range s.s {
          sum += i
      }
  
      return sum
  }
  
  func (s Slicer) Sum() int {
      sum := s.sumSlice()
  
      return sum
  }
  ```

I can try to figure out where and why this is not working, but I would need some pointers to where to look at.

**Comment by teddylear** [comment]
@zemzale I think I know what the issue is, I can try to make a quick PR today or tomorrow.

**Comment by teddylear** [comment]
@zemzale Merged a fix for this, Lmk if this is still an issue.

**Comment by zemzale** [comment]
@teddylear Works like a charm now. Thanks for this 👍
