### ISSUE TITLE
How to use with vim-plug

### ISSUE THREAD

**Issue by amitavaghosh1** [ThePrimeagen/refactoring.nvim#224]
This is more of a how to question. I have vim-plug. My init.vim looks like:

```
Plug 'ThePrimeagen/refactoring.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-treesitter/nvim-treesitter'
```

I also have done `:TSInstall go` and `:TSInstall javascrript` , But how do I do this, `require('refactoring').setup({})` thinggy. 

I tried to see if anything like `:refactoring#setup`, but it doesn't (which is expected, because I couldn't find anything in :help)

Can you please also add an instruction on how to use this?

nvim --version:
```
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by _nixbld1

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/xxx-neovim-unwrapped-0.5.1/share/nvim
```

**Comment by teddylear** [comment]
@amitavaghosh1 this plugin only works on nightly neovim, please update to nightly build and let us know if there is still an issue.

**Comment by amitavaghosh1** [comment]
Oh, that's why I probably kept getting error like:
```
Error detected while processing /Users/amitava.ghosh/.config/nvim/init.vim:
line   98:
E5108: Error executing lua [string ":lua"]:1: module 'refactoring' not found:
```

okay I will try with nightly and repoen the discussion if requirerd.

thanks for getting back
