### ISSUE TITLE
Cursor should stay in same position after extracting method

### ISSUE THREAD

**Issue by ethanfischer** [ThePrimeagen/refactoring.nvim#24]
In Visual Studio, intellisense offers the ability to extract a method from whatever you have highlighted at the time. When you do this, it creates the method and places your cursor where the method is now being called 

Example:

`void main()
{
    var a = ExtractedMethod(); //<--cursor should be on this line. Not inside the ExtractedMethod implementation
}`

**Comment by ThePrimeagen** [comment]
I totally agree!  

This should be an easy fix

**Comment by ThePrimeagen** [comment]
I have moved this to high priority.  I really want this fixed @ethanfischer  

Also going to be tackling the config soon to start adding options.

You could imagine the following

```lua
...
move_cursor = "split_view", "change", "keep",
...
```

Thoughts on this side feature?

**Comment by ethanfischer** [comment]
Love that idea!

**Comment by ThePrimeagen** [comment]
this is mostly done.  The only thing left is to have a new enough version of neovim that it doesn't error :)
