### ISSUE TITLE
[Option] cleanup whole lines

### ISSUE THREAD

**Issue by ofirgall** [ThePrimeagen/refactoring.nvim#271]
`debug.cleanup` cleans up the prints but leaving the added lines empty, can we add `cleanup_lines` boolean to delete the whole line with the print functions?

**Comment by pranavrao145** [comment]
@ofirgall this sounds like a good idea to me - I actually think it should be the default behaviour. We will work on it!

**Comment by teddylear** [comment]
Merged in feature for this, closing.
