### ISSUE TITLE
Multiple debug prints in the same function

### ISSUE THREAD

**Issue by ofirgall** [ThePrimeagen/refactoring.nvim#272]
Sometimes you want to add "trace" prints in your function.
Example:
```python
def foo():
	print('foo::1')
	if statment:
		print('foo::2')
		boo()
		print('foo::3')

	print('foo::4')
	doo()
	print('foo::5')
```
Currently if you are trying to add multiple debug prints the first print is ok but the other will be just empty.
Can we support multiple prints with automated indexes?

**Comment by teddylear** [comment]
@ofirgall Let me take a look into this, this is something I want as well.
