### ISSUE TITLE
Expected test result is invalid code (python, 119)

### ISSUE THREAD

**Issue by MarkTuddenham** [ThePrimeagen/refactoring.nvim#274]
https://github.com/ThePrimeagen/refactoring.nvim/blob/14041a39c5828a17d585362725ba7eb4bb906e2e/lua/refactoring/tests/refactor/119/py/example/extract_var.expected.py#L4
is invalidly indented (requires 4 spaces, has 3)

**Comment by pranavrao145** [comment]
@MarkTuddenham unfortunately indentation is still a work in progress, so for now the test does actually yield that code. Later on when we nail down indentation for Python we can update the test results to what it should actually be.

**Comment by MarkTuddenham** [comment]
Yes, thought there should be an issue to keep track that the test's wrong.

Is someone currently working on indentation (python or otherwise)?

**Comment by pranavrao145** [comment]
I believe indentation is primarily being worked on by @teddylear at the moment, but additional PRs are always welcome!

**Comment by TheLeoP** [comment]
@pranavrao145 this issue could be closed now that the Python test files have the correct indentation?

**Comment by pranavrao145** [comment]
Hi @TheLeoP, yes it seems that this particular example has been fixed. However, there are still tests with invalid code, namely `printf` and `extract_block` for Python. I will close this issue and open a new one to log these updates - thanks for the ping!
