### ISSUE TITLE
Golang refactoring not work

### ISSUE THREAD

**Issue by koolay** [ThePrimeagen/refactoring.nvim#276]
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/4273490/158974848-d3b2a378-8470-4435-8af9-7eddef251723.png">

**Comment by ThePrimeagen** [comment]
Can you please add context? Code example that causes this?

It's virtually impossible to do anything with that

**Comment by koolay** [comment]
<img width="1485" alt="image" src="https://user-images.githubusercontent.com/4273490/159104928-88195041-cd9b-4a2e-99b2-fbfd2a628c38.png">

**Comment by pranavrao145** [comment]
Thanks @koolay, we'll check it out and see what we can do about it.

**Comment by teddylear** [comment]
@koolay Creating a similar test here this appears to be working with extracting something like `go <func call>`. What's the `vim.boshiftwidth` you have in the current buffer? This looks like an issue with indenting, but i'm not sure why.

**Comment by teddylear** [comment]
@koolay Any update on this? Else I'll close this out.

**Comment by koolay** [comment]
It works now after upgrading versions of all plugins.
