### ISSUE TITLE
lua > doesn't extract the full function comment

### ISSUE THREAD

**Issue by molleweide** [ThePrimeagen/refactoring.nvim#292]
I am just trying out the plugin and am really excited to learn how it works over time! I am so happy that you guys decided to build this project.

I noticed this when trying out `extract function` feature:

```lua
--- Reload all Neovim configurations
reloader.reload_configs = function()
  config_pre_reload()
  reloader.reload_plugins_definitions()
  reloader.reload_lua_modules(true)
  reload_runtime_files()
  config_post_reload()
end
```

becomes the following when extracting function.

```lua
--- Reload all Neovim conf
local function fn_test()
                            config_pre_reload()
                            reloader.reload_plugins_definitions()
                            reloader.reload_lua_modules(true)
                            reload_runtime_files()
                            config_post_reload()
end

igurations
reloader.reload_configs = function()
fn_test()
end
```

So it seems it doesn't grab the full comment above the function. FYI I tried with `--` and also `---` in the comment. The tripple hyphen comments are generated with `neogen` plugin.

**Comment by molleweide** [comment]
I just realized also that I am also not sure if the comment is supposed to be included in the refactor.

**Comment by teddylear** [comment]
Thanks for logging this! Ah let me look into this, I confirmed the issue for me locally too.

**Comment by molleweide** [comment]
> Thanks for logging this! Ah let me look into this, I confirmed the issue for me locally too. 

I am learning treesitter at the moment so for now this is a little bit too difficult to solve myself ;) but I am really excited about getting to a point where I can contribute something here myself

**Comment by teddylear** [comment]
@molleweide merged in a fix, let me know if that resolves issue

**Comment by molleweide** [comment]
Cool, I will!

**Comment by molleweide** [comment]
Allright, on first try now it seems to work better!
I have to get comfortable with using it now more and report back any errors or things that I notice. 
Hopefully I will be able to understand the source code better soon. I getting more and more of a grasp on ts now.
