### ISSUE TITLE
refactor `inline var`: throws error if no var in visual selection.

### ISSUE THREAD

**Issue by molleweide** [ThePrimeagen/refactoring.nvim#300]
As title sais :)

`attempt to index local node nil`

**Comment by teddylear** [comment]
I think this is as intended currently, but I can add as feature request.

**Comment by molleweide** [comment]
Aah, allright I just made the issue so that it can be checked off.

**Comment by pranavrao145** [comment]
Since this behaviour is as-intended and we offer maps in both visual mode and normal mode for inline variable, I will close this issue for now - feel free to reopen if needed in the future!
