### ISSUE TITLE
How to adjust console.log statements

### ISSUE THREAD

**Issue by mattiasbonte** [ThePrimeagen/refactoring.nvim#304]
Hi, 

**Context**
I'm currently trying out this plug but am failing miserably at something very simple?
I can't seem to change the `console_log` statements for `JS/TS`.

**Config**
```
require("refactoring").setup({
	-- overrides
	printf_statements = {
		js = {
			'console.log("🟥 someLog %%s %s", %s");',
		},
		ts = {
			'console.log("🟥 someLog %%s %s", %s");',
		},
	},
	print_var_statements = {
		js = {
			'console.log("🟥 someLog %%s %s", %s");',
		}
		,
		ts = {
			'console.log("🟥 someLog %%s %s", %s");',
		},
	},
})
```

**Result**
_`printf` functionality_
 `console.log("getFlowReportFilesZipped");// __AUTO_GENERATED_PRINTF__`

_`print_var` functionality_ 
`console.log("getFlowReportFilesZipped kafka: %s", kafka);// __AUTO_GENERATED_PRINT_VAR__`

**Question**
Am I doing something wrong, is it impossible to change the body of the log statements like this, or am I not understanding the intended use of these debug logs? 
In my mind, I select a variable, execute the print_var function and then a log statement with my variable name inside and some more meta data should be printed.

Cheers.

**Comment by teddylear** [comment]
@mattiasbonte Thanks for raising the issue! I just confirmed this is broken for me as well, so it doesn't look like anything is wrong with your config. Let me take a look and try to get a fix out this week. I'll post here once something is merged for you to take a look at.

**Comment by teddylear** [comment]
@mattiasbonte Upon looking more into this, I think the issue is that you have to move `ts` to `typescript` and `js` to `javascript`. It looks likes the config for each language in `printf_statements` and `print_var_statements` needs to be the treesitter name for the language, not the filetype. Also the `printf` statements would just have one placeholder like `console.log("🟥 someLog %s");` while `print_var` statements should be something like `console.log("🟥 someLog %s %%s", %s");`. Please let me know if these suggestions work for you or if you have any questions. If they do work, I'll update the docs to make this more clear for others. Once again, thanks for opening this issue.

**Comment by mattiasbonte** [comment]
Hey @teddylear, thank you for the quick reply. Changing it to `javascript` and `typescript` does indeed work thank you! 

It will now prompt me to select from 2 options. Which makes me wonder why. This happens for both `printf` and `print_var`. 
![image](https://user-images.githubusercontent.com/65280774/169135886-dc4f8257-cc24-4d99-8707-229617fb049a.png)
![image](https://user-images.githubusercontent.com/65280774/169135939-06ad1536-a4fb-408b-9fc1-f4b76c17d1b7.png)

```
	printf_statements = {
		javascript = {
			'console.log("🟥 %s");',
		},
		typescript = {
			'console.log("🟥 %s");',
		},
	},
	print_var_statements = {
		javascript = {
			'console.log("🟥 %s %%s, %s");',
		}
		,
		typescript = {
			'console.log("🟥 %s %%s, %s");',
		},
	},
```

I also noticed that when selecting, the variable `archive` in the function below and running the `print_var` that this is the given output.
```
function zipDirToBuffer(path) {
	const **archive** = new AdmZip();

	archive.addLocalFolder(path);

	return archive.toBuffer();
}

```
output `print_var`
`console.log("🟥 zipDirToBuffer a: %s, a");// __AUTO_GENERATED_PRINT_VAR__`
output `printf`
`console.log("🟥 zipDirToBuffer");// __AUTO_GENERATED_PRINTF__`

And when running the `debug.cleanup` function it deletes the text but not the actual line, is this the expected behavior?

**Comment by teddylear** [comment]
@mattiasbonte Let me look into the print var issue mentioned with printing the whole variable, but a responding to few things you mentioned:

- The prompt for custom printf/print_var is intended with giving all print options, but I agree that with one custom printf/print_var being set for a language we should just default to using that. I can make an issue for that

- For the lines left behind for `debug.cleanup` I agree as well that's undesirable, I can create a ticket to track that as well. 

- I'll also update the docs for print/print_var to avoid this confusion in the future. 

If there's anything else I missed here please let me know. .

**Comment by mattiasbonte** [comment]
Some more info regarding the `print_var` functionality. 

- I noticed that when my cursor is on the `a` of `archive` and then I select with `v` `llllllll` to select the whole word, it will print out the full `archive` variable. 
- But if I select with for example `v` `e` then only the `a` (first letter of selection) is printed.
- If I start my selection on `c` and select with `viw` then only `c` is printed.

So the solution (for now) is to manually select a word on the first letter `v` `llllllll` until the end of the word.

**Comment by pranavrao145** [comment]
Hi @mattiasbonte, thanks for opening an issue. I've just merged in #307 to make sure it doesn't prompt if there's only one custom statement set. If you update your plugins, you should be able to see it now. Take a look and let us know what you think!

**Comment by teddylear** [comment]
@mattiasbonte Also merged in feature to completely remove lines added by printf/print_var on the latest version of plugin.

**Comment by mattiasbonte** [comment]
You guys are awesome! Ill take a look after the weekend and let you know.

**Comment by teddylear** [comment]
> Some more info regarding the `print_var` functionality.
> 
> * I noticed that when my cursor is on the `a` of `archive` and then I select with `v` `llllllll` to select the whole word, it will print out the full `archive` variable.
> * But if I select with for example `v` `e` then only the `a` (first letter of selection) is printed.
> * If I start my selection on `c` and select with `viw` then only `c` is printed.
> 
> So the solution (for now) is to manually select a word on the first letter `v` and press `llllllll..` until the end of the word.

@mattiasbonte Looking a built points 2 and 3, I have validated they are working as intended for me locally. For bullet point 2 have a test case for this with this [print_var command file](https://github.com/teddylear/refactoring.nvim/blob/master/lua/refactoring/tests/debug/print_var/py/simple-function/print_var.commands#L1-L2) using `ve` commands with [this start file](https://github.com/teddylear/refactoring.nvim/blob/master/lua/refactoring/tests/debug/print_var/py/simple-function/print_var.start.py#L4) and this [end file](https://github.com/teddylear/refactoring.nvim/blob/master/lua/refactoring/tests/debug/print_var/py/simple-function/print_var.expected.py#L5).

For my local config I am using the following configuration as a keymap: 
```lua
    map(
        "v",
        "<Leader>dv",
        [[<Esc><Cmd>lua require("refactoring").debug.print_var({})<CR>]],
        { noremap = true, silent = true, expr = false }
    )
```
I am using `ve` then executing this keymap to print var in the above test case locally. Please let me know if this helps fix the issue and what your config is so I can dig deeper into this if it's still an issue. 

@pranavrao145 Do you mind trying this locally as well? Wanted to make sure this wasn't an issue with my machine.

**Comment by pranavrao145** [comment]
@teddylear tried it out and can confirm that `print_var` works as intended for bullet points 2 and 3.

**Comment by mattiasbonte** [comment]
I have tested this, but it still performed weirdly on my end. I've then changed my keybinding to yours and it looks like its working as expected now!

I've changed `	["<leader>rv"] = { "<CMD>lua require('refactoring').debug.print_var({})<CR>", "Print Variable" },`
To this `	["<leader>rv"] = { "<Esc><Cmd>lua require('refactoring').debug.print_var({})<CR>", "Print Variable" },`

(I'm using the which-key plugin to bind my keys). I guess the `<Esc>` before solved the issue for me..

And about the prompt, it seems to not be prompting me anymore. 
Nice work guys, thank you!
