### ISSUE TITLE
Do not prompt for printf/print_var when one custom printf/print_var set for language

### ISSUE THREAD

**Issue by teddylear** [ThePrimeagen/refactoring.nvim#305]
As mentioned in #304, it would be a better user experience if when setting one custom printf or print_var statement for a language it just defaulted to that. If there is more than one, then prompt the user. Ideally if they want the default as an option, they add that to custom as well.

**Comment by pranavrao145** [comment]
This makes sense to me. I will merge in #307 to fix this.
