### ISSUE TITLE
Print_var no longer prints class attributes 

### ISSUE THREAD

**Issue by shawnyu5** [ThePrimeagen/refactoring.nvim#316]
In javascript, if I have the following code:

```js
let apple = person.name
```

And I highlight `person.name`, and run `:lua require('refactoring').debug.print_var({})` in visual mode. I get 

```
console.log(" person: %s", person); // __AUTO_GENERATED_PRINT_VAR__
```
Where `.name` attribute is not printed.

Expected behaviour: 

```
console.log("person.name: %s", person.name); // __AUTO_GENERATED_PRINT_VAR__
```
It prints out what I selected in visual mode, including the class attributes, with no modification

Not sure if this is a design decision or a bug. I only noticed this change in behaviour recently.

I am running the latest stable neovim version:

```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by pranavrao145** [comment]
Cool, I've gone ahead and reverted #314 - this means that there is still normal mode support (that was in a previous PR), but visually selecting something will not attempt to find the variable anymore and just print whatever is selected (just like before normal mode support was ever introduced). 

@shawnyu5 try updating the plugin and let us know if that fixes the problem!

**Comment by shawnyu5** [comment]
yes, the behaviour is as expected now. Thanks for the quick fix!

**Comment by pranavrao145** [comment]
No problem! I'll close this issue now then.
