### ISSUE TITLE
Setup help/guide

### ISSUE THREAD

**Issue by fabianschwarzfritz** [ThePrimeagen/refactoring.nvim#32]
Hi @ThePrimeagen ,

this is an absolute cool project, the Refactoring book has boosted my skill level like nothing else, even not vim. I'd love to contribute. 

It's most likely a **_setup issue on my machine_**, I am also not the Neovim-plug-pro yet. I know GH issues are no place for setup help - however, I really don't know where else to look/check.... Maybe you have some ideas on how to set this up for development?

I have installed neovim:
```bash
nvim --version
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
```

and the plugins you mentioned via `vim-plug`, the installation works:
```
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-treesitter/nvim-treesitter'
Plug 'tree-sitter/tree-sitter-typescript'
Plug '~/refactoring.nvim'
```
while `~/refactoring.vim` this repo cloned (last clone 8th of August) evening, latest and greatest version.

However when starting I get tons of errors. Here are examples for `re`  `rt` with the test file from this project `nvim ~/refactoring.nvim/lua/refactoring/tests/extract.simple-function.start.ts`.

`<leader> re`:
```
E5108: Error executing lua ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: The 
coroutine failed with this message: ...start/refactoring.nvim/lua/refactoring/pipeline/init.lua
:58: Scope is nil
```

`<leader>rt`
```
E5108: Error executing lua ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:2: modul
e 'popup' not found:
        no field package.preload['popup']
        no file './popup.lua'
        no file '/Users/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/popup.lua'

        no file '/usr/local/share/lua/5.1/popup.lua'
        no file '/usr/local/share/lua/5.1/popup/init.lua'
        no file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/popup.lua'
        no file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/popup/init.lua'
        no file './popup.so'
        no file '/usr/local/lib/lua/5.1/popup.so'
        no file '/Users/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/popup.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```

Where do I start from here? Any hint what's missing in my project installation?

**Comment by ThePrimeagen** [comment]
could you provide the code you have highlighted?  Or a brief form of it?

Also I don't know what `<leader>re` I assume refactor extract function.

If you could provide me what you have highlighted that would be great.  It looks like you have some sort of telescope issue.  Do you have telescope installed?  What does <leader>re do?

My guess is that you have something that needs to be worked out with the first one, and the second one I assume is a library issue (potentially).

Lastly, you don't need tree-sitter-typescript.  You can simply `:TSInstall typescript` and it should be enough to run these plugins.  I am working pretty hard on hardening and making master the bestest its ever been.  Thanks for taking the time to make an issue with lots of detail.

**Comment by ThePrimeagen** [comment]
You will need `plenary` for development. 

https://github.com/nvim-lua/plenary.nvim

**Comment by fabianschwarzfritz** [comment]
Hi @ThePrimeagen ,

thanks for the quick reply 🥇 . These are actually two issues, so I have split them.

### **Issue "refactor extract function"**
> could you provide the code you have highlighted? Or a brief form of it?

Sure, I used one of the test files in this repository, [extract.simple-function.start.ts](https://github.com/ThePrimeagen/refactoring.nvim/blob/master/lua/refactoring/tests/extract.simple-function.start.ts) . I did highlight lines 4-6 (both including) with vim's visual line highlighting mode, so that 4-6 are completely selected. Here's a screenshot:
<img width="611" alt="Bildschirmfoto 2021-08-09 um 20 17 38" src="https://user-images.githubusercontent.com/1759672/128754304-11263e82-d9c7-49d7-a7a1-77f8ac2ed5c8.png">


> Also I don't know what <leader>re I assume refactor extract function.

Exactly, that's what I meant

Yes, I have telescope  and plenary installed, these are the installed plugins on my machine:
```vim
" Refactoring.nvim on local machine and the lib's dependencies
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-treesitter/nvim-treesitter'
Plug 'tree-sitter/tree-sitter-typescript'
Plug '~/refactoring.nvim'
```

Here comes the interesting part.

When I open a new editor, mark the line and "refactor extract function" as described above, it fails with the error. If I then add your suggested `:TSInstall typescript`, afterwards I can do the refactoring _successfully_ on that open nvim session/instance. This is funny, because when doing that I get a warning "is already installed, do you want to reinstall..."

This works until I close nvim and open nvim again. When mark the same selection in the newly opened nvim, do "refactor extract function", then, the same issue appears again. I can then (again) resolve it with `:TSInstall typescript`....

### **Issue "display refactoring"**
I can get one step further by adding popup to my installation `Plug 'nvim-lua/popup.nvim'`. then everything works 👍🏻 . I should have read this in the [telescope.nvim documentation here](https://github.com/nvim-telescope/telescope.nvim#installation).

I'll add a PR to add the `popup.nvim`/`plenary.nvim` lib to the sample packer setup `require` section, and add a hint that one has to `TSInstall`.

So the only thing left wrt issue is the first point, why I have to  `TSInstall typescript` after each time opening a new `nvim`. 

Cheers, Fabian

**Comment by teddylear** [comment]
@fabianschwarzfritz Is this still an issue? I think the plugin is more stable as this point.
