### ISSUE TITLE
 [Q] Why the use of visual mode?

### ISSUE THREAD

**Issue by LamprosPitsillos** [ThePrimeagen/refactoring.nvim#321]
Really useful plugin , thanks for maintaining it!
My question is since we have tree-sitter why doesn't the plugin use it in some cases,relying on visual mode instead?
Is there a way to enable this behavior?
For example , i want to have my cursor on the variable and then call the print_var function, instead of selecting it.

**Comment by teddylear** [comment]
@LamprosPitsillos Thanks for opening issue! We did have a pull request for this and made it the default behavior, but found that it doesn't cover all cases (like printing a field on a specific class, etc) so we ended up reverting it. While this would be the preferred behavior, I don't think we can maintain having this work for all cases and would default to the highlight case as well. 

If this is something that people want I have been been considering the idea of making a separate debug function or setting that would enable this sort of behavior without breaking the visual mode one. @pranavrao145 What are your thoughts on doing something like that? If it's split off or a setting, then at least we have the visual mode `print_var` to fallback to while a normal `print_var` can be used for majority of cases if people desire.

**Comment by teddylear** [comment]
This way if we wanted to expand the normal mode `print_var` functionality as well so support these custom use cases, we could do that as well.

**Comment by LamprosPitsillos** [comment]
That sounds like a great idea!
Also i found out that i can achieve this behavior with treesitters incremental selection. 
But it would be great to skip over this "extra step" and go straight to refactoring.

**Comment by teddylear** [comment]
@pranavrao145 I'll start working on this and PR what I'm thinking so we can discuss there.

**Comment by teddylear** [comment]
@LamprosPitsillos We recently merged in a change to use this all the time by passsing `{ normal = true}` to the `print_var` function and updated the docs to reflect this. Please let us know if you have any more questions or issues with this, else we'll close this out.
