### ISSUE TITLE
Start the official readme.  Time to get serial about this project.

### ISSUE THREAD

**Issue by ThePrimeagen** [ThePrimeagen/refactoring.nvim#33]

**Comment by David-Else** [comment]
Just wanted to say I am REALLY looking forward to using this extension! I await a readme before I try it, as I am not really sure what it can do yet.

The closest tool I know of is 🧙‍ Abracadabra https://github.com/nicoespeon/abracadabra , which is VS Code and JS/TS only. He is also going full Martin Fowler, so some of the code might interest you!

**Comment by teddylear** [comment]
Have a solid README at this point, I think we are close to being super duper cereal
