### ISSUE TITLE
Can't find default keybindings in documentation

### ISSUE THREAD

**Issue by mkastner** [ThePrimeagen/refactoring.nvim#333]
I am wondering whether there exist any default keybindings for refactoring. I couldn't find them in the documentation.

**Comment by pranavrao145** [comment]
Hi @mkastner, 

There are no default keybindings that come with the plugin, but there are several different ways you can make your own as described in the README. Take a look at the different options (Telescope, in-built selections, direct keymaps), and feel free to post here if you have any questions!

**Comment by mkastner** [comment]
Hi @pranavrao145,

thanks for the helpful clarification and info.

**Comment by mkastner** [comment]
Hi @pranavrao145,

thanks for the helpful clarification and info.
