### ISSUE TITLE
Error performing any action

### ISSUE THREAD

**Issue by IagoQ** [ThePrimeagen/refactoring.nvim#334]
I'm having issues using the plugin anytime that I try to trigger an action this error shows up:
`E5108: Error executing lua ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...start/refactoring.nvim/lua/refactoring/pipeline/init.lua
:61: Scope is nil
stack traceback:
        [C]: in function 'error'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:40: in function 'step'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:43: in function 'execute'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:113: in function <...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:112>
        ...start/refactoring.nvim/lua/refactoring/pipeline/init.lua:70: in function 'run'
        .../start/refactoring.nvim/lua/refactoring/refactor/106.lua:533: in function <.../start/refactoring.nvim/lua/refactoring/refactor/106.lua:514>
        ...k/packer/start/refactoring.nvim/lua/refactoring/init.lua:31: in function 'refactor'
        ...factoring.nvim/lua/telescope/_extensions/refactoring.lua:8: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:338: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk`

I'm currently working with Golang

**Comment by teddylear** [comment]
@IagoQ Thanks for creating issue! Can you share the config you are using the steps to reproduce issue. I just ran the tests on master and there were to failing ruby tests, but all of Golang should be working.

**Comment by IagoQ** [comment]
![image](https://user-images.githubusercontent.com/26334181/188241005-51654714-84c7-4208-9f9d-829ac7a45995.png)

for example trying to extract those 3 lines to a function fails with the error

my config is the default one, using the telescope keymap
```require('refactoring').setup({}) ```

```lua require('telescope').extensions.refactoring.refactors()<CR>",```

**Comment by teddylear** [comment]
@lagoQ Are those lines inside a function? By the indentation I'm assuming so. If not, please let me see more of the file you are working on if possible because it's most likely a missing scope in the plugin for golang. Also, are you going to from visual mode back to normal mode before calling the telescope command? The plugin requires doing so so that the text selection works.

**Comment by IagoQ** [comment]
After a little more testing i've discovered that it only fails on files that use go generics (and not always) it seems that sometimes the new generic syntax bugs out the treesitter making it parse the file wrong, the color for some token changes when I add or remove the generic line. I have all my parsers up to date, It seems that the go parser isn't updated to support generics?

**Comment by teddylear** [comment]
@IagoQ It is likely that the  refactoring plugin is missing the treesitter query for the go generics syntax. Can you provide a code example (before and after) of what you are trying to extract with using generics? I can use that to create a test and add the query for this new functionality.

**Comment by IagoQ** [comment]
After some tinkering I seem to have it reduced as much as I could.
[test.zip](https://github.com/ThePrimeagen/refactoring.nvim/files/9483359/test.zip)
 
This (after creating a go mod file) seems to be enough to break the highlighting and make the refactoring fail.
![image](https://user-images.githubusercontent.com/26334181/188287199-6e5306d3-5854-45d7-be92-05c693476fb3.png)

Notice that after removing the generic param the highlight fixes itself (mainly the method color) and the plugin works on the testfunc

![image](https://user-images.githubusercontent.com/26334181/188287245-a59491dc-6032-45f4-8929-7fc0d0f1d21b.png)

**Comment by davemackintosh** [comment]
I am also seeing this error when trying to refactor things in Lua and in Go.

**Comment by ThePrimeagen** [comment]
looks like we haev ourselves a bit of an issue!

i am going to be coming back online for this project in the next couple of weeks.  So i will be reviewing and hopefully creating a lot more functionality :)  this can be one of the first things i look at.

**Comment by davemackintosh** [comment]
Thanks! I'll try to take a look later too to help debug.

**Comment by jeffschwartz** [comment]
I don't know if this is related or not but every action I take with refactoring ends in this:
```
E5108: Error executing lua ...re/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...50460c_1/share/nvim/runtim
e/lua/vim/treesitter/query.lua:532: attempt to index local 'node' (a nil value)
stack traceback:
        [C]: in function 'error'
        ...re/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
        ...re/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:45: in function 'on_confirm'
        .../neovim/HEAD-c50460c_1/share/nvim/runtime/lua/vim/ui.lua:93: in function 'input'
        ...m/plugged/refactoring.nvim/lua/refactoring/get_input.lua:8: in function 'returned_function'
        ...re/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:31: in function 'callback_or_next'
        ...re/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:45: in function 'on_confirm'
        .../neovim/HEAD-c50460c_1/share/nvim/runtime/lua/vim/ui.lua:93: in function 'input'
        ...m/plugged/refactoring.nvim/lua/refactoring/get_input.lua:8: in function 'returned_function'
        ...re/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:31: in function 'callback_or_next'
        ...re/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:45: in function 'step'
        ...re/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:48: in function 'execute'
        ...re/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:118: in function <...re/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:117>
        ...ugged/refactoring.nvim/lua/refactoring/pipeline/init.lua:70: in function 'run'
        ...lugged/refactoring.nvim/lua/refactoring/refactor/106.lua:568: in function <...lugged/refactoring.nvim/lua/refactoring/refactor/106.lua:553>
        ...e/nvim/plugged/refactoring.nvim/lua/refactoring/init.lua:31: in function 'refactor'
        ...e/nvim/plugged/refactoring.nvim/lua/refactoring/init.lua:49: in function 'select_refactor'
        [string ":lua"]:1: in main chunk
```
My config:
```lua
require('refactoring').setup({})

-- Remaps for the refactoring operations currently offered by the plugin
vim.api.nvim_set_keymap("v", "<leader>re", [[ <Esc><Cmd>lua require('refactoring').refactor('Extract Function')<CR>]], {noremap = true, silent = true, expr = false})
vim.api.nvim_set_keymap("v", "<leader>rf", [[ <Esc><Cmd>lua require('refactoring').refactor('Extract Function To File')<CR>]], {noremap = true, silent = true, expr = false})
vim.api.nvim_set_keymap("v", "<leader>rv", [[ <Esc><Cmd>lua require('refactoring').refactor('Extract Variable')<CR>]], {noremap = true, silent = true, expr = false})
vim.api.nvim_set_keymap("v", "<leader>ri", [[ <Esc><Cmd>lua require('refactoring').refactor('Inline Variable')<CR>]], {noremap = true, silent = true, expr = false})

-- Extract block doesn't need visual mode
vim.api.nvim_set_keymap("n", "<leader>rb", [[ <Cmd>lua require('refactoring').refactor('Extract Block')<CR>]], {noremap = true, silent = true, expr = false})
vim.api.nvim_set_keymap("n", "<leader>rbf", [[ <Cmd>lua require('refactoring').refactor('Extract Block To File')<CR>]], {noremap = true, silent = true, expr = false})

-- Inline variable can also pick up the identifier currently under the cursor without visual mode
vim.api.nvim_set_keymap("n", "<leader>ri", [[ <Cmd>lua require('refactoring').refactor('Inline Variable')<CR>]], {noremap = true, silent = true, expr = false})

-- prompt for a refactor to apply when the remap is triggered
vim.api.nvim_set_keymap(
    "v",
    "<leader>rr",
    ":lua require('refactoring').select_refactor()<CR>",
    { noremap = true, silent = true, expr = false }
)
```
The code that I am attempting to refactor (extract block) is the `markerFindAndReplaceContent` function from the following file:
```js
import matter from "gray-matter";
import { ignoreTokens } from "./ignoreTokens.js";

const markerFindAndReplaceContent = function(content: string, marker: string, value: string): string {
    const _content = content;
    return _content.replace(new RegExp(`{${marker}}`, "g"), `${value}`);
};

export const composeWithoutTemplate = async function(asset: AssetType): Promise<AssetType> {
    const fm = matter(asset.content as string);
    for (const [key, value] of Object.entries(fm.data)) {
        if (!ignoreTokens.includes(key)) {
            fm.content = markerFindAndReplaceContent(fm.content, key, value);
            console.log("fm.content", fm.content);
        }
    }
    return asset;
};
```

**Comment by teddylear** [comment]
@IagoQ Sorry just getting back to this, but thank you for the code snippets and info. I can try to get a test case with this working this week, but from what you're describing it sounds like the `golang` treesitter parser may not support generics yet. If this is the case I can validate that and try to make an issue on the upstream parser (though they may have added support for it by now). 

@jeffschwartz @davemackintosh Could you please make separate issues with similar code snippets and details? I don't want to load multiple issues onto one thread and it appears that these are different issues than the main one with the `golang` parser.

**Comment by teddylear** [comment]
@IagoQ Sorry for the delay, I confirmed this was an issue with the upstream parser a while ago. Is this still an issue? If so I can try to make an issue on the upstream parser.

**Comment by shinobu-uwu** [comment]
@teddylear i just started using this plugin and i'm facing the same issue with a rust file, my config is basically the one in the README
```
require('refactoring').setup({
    -- prompt for return type
    prompt_func_return_type = {
        go = true,
        cpp = true,
        c = true,
        java = true,
        php = true,
        rust = true
    },
    -- prompt for function parameters
    prompt_func_param_type = {
        go = true,
        cpp = true,
        c = true,
        java = true,
        php = true,
        rust = true,
    },
})
require("telescope").load_extension("refactoring")
-- prompt for a refactor to apply when the remap is triggered
vim.api.nvim_set_keymap(
    "v",
    "<leader>rr",
    "<Esc><cmd>lua require('telescope').extensions.refactoring.refactors()<CR>",
    { noremap = true }
)
-- Remaps for the refactoring operations currently offered by the plugin
vim.api.nvim_set_keymap("v", "<leader>xm", [[ <Esc><Cmd>lua require('refactoring').refactor('Extract Function')<CR>]],
    { noremap = true, silent = true, expr = false })
vim.api.nvim_set_keymap("v", "<leader>xmf",
    [[ <Esc><Cmd>lua require('refactoring').refactor('Extract Function To File')<CR>]],
    { noremap = true, silent = true, expr = false })
vim.api.nvim_set_keymap("v", "<leader>xv", [[ <Esc><Cmd>lua require('refactoring').refactor('Extract Variable')<CR>]],
    { noremap = true, silent = true, expr = false })
vim.api.nvim_set_keymap("v", "<leader>iv", [[ <Esc><Cmd>lua require('refactoring').refactor('Inline Variable')<CR>]],
    { noremap = true, silent = true, expr = false })

-- Inline variable can also pick up the identifier currently under the cursor without visual mode
vim.api.nvim_set_keymap("n", "<leader>iv", [[ <Cmd>lua require('refactoring').refactor('Inline Variable')<CR>]],
    { noremap = true, silent = true, expr = false })
```

**Comment by teddylear** [comment]
@shinobu-uwu We do not currently support rust for the plugin.

**Comment by teddylear** [comment]
@IagoQ Going to close as this appears to be an issue with upstream parser. Please create an issue on stream treesitter parser for what you are seeing.
