### ISSUE TITLE
Multiple return values in extracted python function

### ISSUE THREAD

**Issue by AckslD** [ThePrimeagen/refactoring.nvim#338]
Lets say you have the python buffer:
```python
a = 1
b = 1

print(a)
print(b)
```
and the two first lines visually selected (assignment of the variables) and extract a function with name `func`. I then get
```python

def func():
    a = 1
    b = 1
    return a, b


a = func()


print(a)
print(b)
```
where the function is correct however it's return value is then assigned to `a` instead of `a, b = func()`.

**Comment by pranavrao145** [comment]
Hi @AckslD, sorry for the late response - thanks for opening an issue! I've fixed this and added a test for it in #349, which should be merged shortly.
