### ISSUE TITLE
Refactorings for c#

### ISSUE THREAD

**Issue by SaschaDoe** [ThePrimeagen/refactoring.nvim#342]
Hey, it World be nice to have Code refactorings for c# too.

**Comment by Tantol** [comment]
Man can we have some coconut oil for c# blazingly fast coding?

**Comment by joviol** [comment]
Any ETA for C# support?

**Comment by TheLeoP** [comment]
There isn't an ETA right now. PRs are welcomed and I'm happy to guide anyone on how to add support to it, though

**Comment by vijairamg** [comment]
@TheLeoP 
Hi, I'm interested in getting it working for c#. What are the high level steps to implement it?

**Comment by TheLeoP** [comment]
@vijairamg 

- adding a `cs.lua` file on the `lua/refactoring/treesitter/langs` with the necessary queries (you can use the builtin Neovim command `:InspectTree` inside of a c# file to check the nodes and test the queries)
- adding a `cs.lua` file on the `lua/refactoring/code_generation/langs` with the necessary functions (i.e. a template for a function, a class, etc)
- adding tests for each c# refactor that you are adding support to (check `lua/refactoring/tests/refactor`)

You can use the lua (or any other language) support as a guide:

https://github.com/ThePrimeagen/refactoring.nvim/blob/d07218748c48e756c27aa6859bfa6e62a3d271af/lua/refactoring/treesitter/langs/lua.lua

https://github.com/ThePrimeagen/refactoring.nvim/blob/d07218748c48e756c27aa6859bfa6e62a3d271af/lua/refactoring/code_generation/langs/lua.lua

Have you used treesitter before? If no, you'll need to read [its documentation](https://tree-sitter.github.io/tree-sitter/using-parsers#query-syntax) to understand its query syntax.

**Comment by vijairamg** [comment]
Thanks for the pointers. 

I don't know much about tree sitter (other than InspectTree).

**Comment by TheLeoP** [comment]
@vijairamg let me know if you want some help c:
