### ISSUE TITLE
Refactoring for Go and Lua

### ISSUE THREAD

**Issue by maximyurevich** [ThePrimeagen/refactoring.nvim#343]
Refactoring for go and lua doesn't working for extract variable

**Comment by TheLeoP** [comment]
Could you provide an example of when and how extract variable doesn't work?

**Comment by maximyurevich** [comment]
> Could you provide an example of when and how extract variable doesn't work?
For example
`
package init

import "fmt"

func main() {
	a := 2
	fmt.Println(a)
	foo()
}

func foo() {
	fmt.Printf("foo")
}
`
A lot of refactoring functions doesn't work as expected, especially in go

**Comment by maximyurevich** [comment]
After visual refactoring I had to shut down my computer, in normal mode I got something similar to "Scope is nil" with golang.

**Comment by TheLeoP** [comment]
> After visual refactoring I had to shut down my computer, in normal mode I got something similar to "Scope is nil" with golang.

There is no normal and visual mode refactoring. You should select the are using visual mode, press escape and then call the refactoring function (or press escape and call the function using a keymap)

In your example, what exactly are you selecting, what function are you calling and which is the exact error being shown?

**Comment by maximyurevich** [comment]
> There is no normal and visual mode refactoring. You should select the are using visual mode, press escape and then call the refactoring function (or press escape and call the function using a keymap)
> 
> In your example, what exactly are you selecting, what function are you calling and which is the exact error being shown?

Memory leak after variable extract

**Comment by TheLeoP** [comment]
Could you provide a video of the error?

**Comment by maximyurevich** [comment]
> Could you provide a video of the error?

No, because I just have a 4 GB of ram and after this I should shutdown my machine, here is a screenshot for python that works https://imgur.com/AHIwYdW.png

**Comment by pranavrao145** [comment]
@maximyurevich thanks for opening an issue! In your Go example, can you please specify what exactly you tried to extract, what the expected result was, and what actually happened? This information will help us to fix this faster.

**Comment by maximyurevich** [comment]
Go:

https://user-images.githubusercontent.com/21293376/208946328-cb2152a2-0925-426b-8166-d3684cf844a1.mp4


https://user-images.githubusercontent.com/21293376/208946907-d227067a-cdc9-4802-8c1f-686e15071e6c.mp4


https://user-images.githubusercontent.com/21293376/208946399-8c7779bc-9df0-4201-bacb-83d5a18e54d7.mp4


https://user-images.githubusercontent.com/21293376/208946722-d2cac2d2-cdb8-4934-ba9b-81a82f45ceaf.mp4


https://user-images.githubusercontent.com/21293376/208946621-64f5d8cf-237b-4b7a-9630-30f99b5ecd7f.mp4


https://user-images.githubusercontent.com/21293376/208946568-7977337d-7293-49c8-b680-27e7da7b7b75.mp4


https://user-images.githubusercontent.com/21293376/208946528-9006439c-073c-4f67-8688-c87bd1a30836.mp4


https://user-images.githubusercontent.com/21293376/208946481-0ce16cc5-5978-41f8-9668-7b7fcd08544b.mp4



Lua:

**Comment by maximyurevich** [comment]
Memory leak is relevant for go when extracting a variable and incorrect behavior when extracting a variable with a single-letter name

https://user-images.githubusercontent.com/21293376/209021784-5d09cca7-bd57-4323-a0d5-1f4aca3659f1.mp4

**Comment by pranavrao145** [comment]
Thanks for providing detail @maximyurevich! 

As for  the extracting function problems, from the recording it looks like you're trying to extract a full top-level function. Actually, `Extract Function` and `Extract Function to File` are intended to be used on a block of code that will be extracted to a separate function, either within the same file or to a different file; the plugin is currently incapable of moving entire functions to different files (that's a good idea for a feature though). Perhaps the documentation can be updated to better reflect this.

As for the single-letter variable inlining problems, I've discovered the issue (which has to do with TreeSitter failing to pick up one-letter variable names as identifiers) and am working on a fix!

**Comment by teddylear** [comment]
@pranavrao145 Is this good to close with PR merged?

**Comment by pranavrao145** [comment]
Yep, good catch - will close now!
