### ISSUE TITLE
Python decorators

### ISSUE THREAD

**Issue by agusdmb** [ThePrimeagen/refactoring.nvim#361]
Hey, great plugin! I'm loving it, but there's just one issue that's bothering me.

When I have more than one decorator on a function and I refactor the code inside of it, the refactored code gets moved up and in between the decorators.

For example:

Before extracting the for loop:
```python
def my_decorator():
    pass

@my_decorator
@my_decorator
@my_decorator
def fun():
    dummy_assignment = None

    for i in range(10):
        dont_do_much += i

    return dont_do_much
```

After extracting the for loop:

```python
def my_decorator():
    pass

@my_decorator
@my_decorator

def extracted_fun():
    for i in range(10):
        dont_do_much += i

@my_decorator
def fun():
    dummy_assignment = None

    extracted_fun()

    return dont_do_much
```

It would also be great if I could set the new function to go below the original one instead of above. That would comply with Uncle Bob's principles.

**Comment by teddylear** [comment]
@agusdmb Let me take a look into this. I can work on the decorators, but extracting blocks below instead of above would probably have to be a separate issue as that's a major rework. I do love the idea though and adding as a configuration would be great, let me make a separate issue for that.

**Comment by teddylear** [comment]
@agusdmb I believe this should be resolve on the latest update. Please let me know if you are still seeing issue.

**Comment by agusdmb** [comment]
@teddylear it does work now!! thank you so much, this is very helpful!

**Comment by teddylear** [comment]
@agusdmb Thanks for checking this is working and thanks again for opening an issue, we really appreciate it.
