### ISSUE TITLE
Support inline function refactoring

### ISSUE THREAD

**Issue by a45s67** [ThePrimeagen/refactoring.nvim#366]
### Description
Hello, I think inline function refactoring is nice in some scenario. Would you consider add this feature in the future?
Thank you~

### Example
``` c++
class PizzaDelivery {
  bool moreThanFiveLateDeliveries() {
    return numberOfLateDeliveries > 5;
  }
  int getRating() {
    return moreThanFiveLateDeliveries() ? 2 : 1;
  }
}
```
To
``` c++
class PizzaDelivery {
  // -------- Deleted --------------------
  // bool moreThanFiveLateDeliveries() {
  //  return numberOfLateDeliveries > 5;
  // }
  int getRating() {
    return numberOfLateDeliveries > 5 ? 2 : 1;
  }
}
```
It can expand the implementation of `moreThanFiveLateDeliveries()` in `getRating()` (what I looking forward most). Then it deletes `moreThanFiveLateDeliveries()` (nice but not necessary for me)

### Reference
- https://blog.jetbrains.com/rscpp/2021/06/25/resharper-cpp-2021-2-eap-inline-function-refactoring/
- https://refactoring.guru/inline-method

**Comment by pranavrao145** [comment]
Hi @a45s67, thanks for opening an issue and sorry for the rather late response. I think function inlining would be a pretty great to have in the future, so I'm going to mark this as a feature request for now, and at some point we can definitely take a look at it!

**Comment by wuilliam321** [comment]
Hi @pranavrao145, I'm not sure if this issue is already taken. But what's the best approach to bring it to live? Can I take it? or maybe sponsor the repo/user to help making it happen?

**Comment by pranavrao145** [comment]
Hi @wuilliam321. As far as I know, no one is working on this right now - if you would like to take a crack at it, by all means - feel free to open a PR and we can take a look and provide feedback!

**Comment by Vinh-CHUC** [comment]
Hi all, I'm confused as the main `README.md` mentions "Inline Function", but it's actually not supported? There's also the "Refactor inline_func" function exposed in vim

I was trying with this very simple example:
```
def hello():
    x = 3
    a = 3 + x + 10
    b = 3 + x + 5
    return a, b


def hi() -> int:
    a, b = hello()
    return a + b
```

In normal mode, having the cursor on the "def hello()" (tried various characters) it says "Error: no function usages to inline"

**Comment by TheLeoP** [comment]
@Vinh-CHUC. Inline function support was indeed added by wuilliam321. I'm closing this issue.

> I was trying with this very simple example:

The tresitter captures needed for each refactor are supported on a best effort basis. Currently, 115 is supported for lua, c and go. #444 should add support for python and improve the error message to show when the plugin can't inline a function and when the filetype is not supported.
