### ISSUE TITLE
Question: Could I be a maintainer of this plugin?

### ISSUE THREAD

**Issue by TheLeoP** [ThePrimeagen/refactoring.nvim#374]
I really like this plugin and I would love to be a maintainer of it. Is this something I could do?

**Comment by pranavrao145** [comment]
Hi @TheLeoP. First of all, thank you for making the many contributions you have over the last few months. Given your consistent high quality contributions over the last bit (like TSX and redoing indentation) and your knowledge of the codebase, I would be on board with making you a maintainer on this project. @teddylear and/or @ThePrimeagen, what do you think about this?

**Comment by teddylear** [comment]
@pranavrao145 @TheLeoP Hey! Sorry haven't been super actively recently with the plugin, I have no problem with @TheLeoP being a maintainer. I don't know if I have permissions though, we might have to reach out to @ThePrimeagen via discord to add @TheLeoP as a maintainer.

**Comment by ThePrimeagen** [comment]
Yes is in order and I owe you several beers

**Comment by ThePrimeagen** [comment]
I'm going to do it in the morning, I'm away from any computers for the evening

**Comment by TheLeoP** [comment]
Hey, @pranavrao145 . Is it rude to ping this issue?

**Comment by pranavrao145** [comment]
Hey @TheLeoP not at all, Prime is a pretty busy dude; it's likely it just slipped his mind. @ThePrimeagen, whenever you get a chance, do you mind making @TheLeoP a collaborator on this repository?

**Comment by pranavrao145** [comment]
@TheLeoP the invitation has been sent - you should be able to accept it now.
