### ISSUE TITLE
[Question] Get the `argument_list` of a `call_expression`

### ISSUE THREAD

**Issue by wuilliam321** [ThePrimeagen/refactoring.nvim#381]
I'm working on this feature https://github.com/ThePrimeagen/refactoring.nvim/issues/366, and I need to get the list of argument that a fuction has, in this case is a `string` but it could be anything, the use case I'm trying to solve now is when it is a plain `string`

![image](https://github.com/ThePrimeagen/refactoring.nvim/assets/236566/384d6e43-a0bc-40d6-ba63-2f823edc1e63)

@TheLeoP any idea! :)

**Comment by TheLeoP** [comment]
@wuilliam321 

You can use `TreeSitter:loop_thru_nodes(scope, self.function_args)` to capture the argument list of any language (it depends on the `function_args` setting of each language, so you should first call `self:validate_setting("function_args")` to error if the setting is not available for a particular language.

**Comment by wuilliam321** [comment]
@TheLeoP 

I have another question, I need to get a list of returned values

![image](https://github.com/ThePrimeagen/refactoring.nvim/assets/236566/bd71d649-1398-42a1-9728-bec8009a090d)

I need to get the value 1 and value 2, and set it to the var `aa` and `bb` respectively 

I have a code (ugly as hell) that does that:
```lua
local returned_values = {}
for _, statement in ipairs(refactor.ts:get_statements(new_declarator_node:parent())) do
    -- TODO: ugly as hell
    if statement:type() == "return_statement" then
        if statement:child(1) then
            local return_value = {}
            local idx = 0
            while type(return_value) ~= nil do
                return_value = statement:child(1):child(idx)
                if return_value == nil then
                    break
                end

                table.insert(returned_values, vim.treesitter.get_node_text(return_value, bufnr))
                idx = idx + 1
            end
        end
    end
end

```
and for some reason this is the output:
```
{ '"test"', ",", '"an error"' }	
```
There is an extra element there `","`, I think there is a better way to do what I need

**Comment by wuilliam321** [comment]
this a temporal solution:
```lua
            for _, statement in ipairs(refactor.ts:get_statements(new_declarator_node:parent())) do
                -- TODO: ugly as hell
                if statement:type() == "return_statement" then
                    if statement:child(1) then
                        local return_value = {}
                        local idx = 0
                        while type(return_value) ~= nil do
                            return_value = statement:child(1):child(idx)
                            if return_value == nil then
                                break
                            end


                            local value = vim.treesitter.get_node_text(return_value, bufnr)
                            if value ~= "," then -- ugly a HELL
                                table.insert(returned_values, value)
                            end
                            idx = idx + 1
                        end
                    end
                end
            end
```

**Comment by TheLeoP** [comment]
I would add a new field to the treesitter instances called something similar to `return_values` and it would have a list of `InlineNode`  that define queries for gettings return values. For example, for `treesitter/langs/go.lua`, the code would be something like the following:

```lua
-- ...
        return_values = {
            InlineNode("(return_statement (expression_list (_) @temp))"),
        },
-- ...
```

And then you could use it just like on my previous answer by `TreeSitter:loop_thru_nodes(scope, self.return_values)`.

The particular query that I used for go captures the following nodes:

![image](https://github.com/ThePrimeagen/refactoring.nvim/assets/53507599/5f812862-a1e9-4c1a-9013-50d6dc03ae2e)

> There is an extra element there ",", I think there is a better way to do what I need

This is because you are using `node:child()`, which also returns anonymous nodes (like `,`), probably you meant to use `node:named_child()`. Check `:h TSNode` ofr more info

**Comment by wuilliam321** [comment]
nice! seems to be working. Now I have another question: my expected code is always out of format, I mean, with bad indentation, I was expecting that the `post_refactor` task would solve that. How can I do that @TheLeoP

**Comment by wuilliam321** [comment]
I think I found the issue, I wasn't returning the refactoring:
before
```lua
...
        :add_task(
        --- @param refactor Refactor
            function(refactor)
                inline_func_setup_new(refactor, bufnr)
            end
        )
```
after:
```lua
        :add_task(
        --- @param refactor Refactor
            function(refactor)
                return inline_func_setup_new(refactor, bufnr)
            end
        )
```
unnoticable xD

**Comment by TheLeoP** [comment]
@wuilliam321 currently, there is no formatting step. Yo can use the `indent` module to define the indentation of a line, but for some complicated use cases, you may need to define it manually and add it to the text_edits. You can check out 106 for an example of this
