### ISSUE TITLE
[Question] Is there a reason for not longer using lsp?

### ISSUE THREAD

**Issue by TheLeoP** [ThePrimeagen/refactoring.nvim#383]
Some parts of the codebase still reference the use of lsp (not the Neovim lsp api like for text edits, but doing requests to external language servers using the neovim client) and checking out really old commits I found that this plugin used to make requests to external language servers. Is there a reason why this is no longer the case?

**Comment by teddylear** [comment]
@TheLeo If I'm remembering correctly, we found that we could do most of the desired refactors just via treesitter, which was much more lightweight than doing the same operations than using an LSP (at least that's what I remember, things could have changed by now). The other issue was adding multiple lsp's do the CI was a giant headache that also extended the runtime by a lot. So I would be hesitant to add back using lsp unless there was a good use case for using one. Where you thinking of using one for a specific use case?

**Comment by TheLeoP** [comment]
@teddylear Thanks for the answer. I was just confused with some parts of the code (particularly the `lsp.lua` file). Diggin a bit in older commits I fond that this was once used, but it no longer is. So, since the plugin isn't using LSP right now, is safe to remove this parts of the codebase?

**Comment by pranavrao145** [comment]
Hmm I never even noticed that. I think if we aren't using it we could probably get rid of it. Later on if we manage the task of actually integrating LSP into this plugin, we can pull related files out of the commit history.
