### ISSUE TITLE
Multi-line print_var cleanup only deletes the line with the comment

### ISSUE THREAD

**Issue by rafaelderolez** [ThePrimeagen/refactoring.nvim#388]
I was using ﻿`debug.print_var()` and it resulted in a lengthy ﻿console.log(). My Prettier config formatted it into multiple lines. When attempting to use ﻿`debug.cleanup()`, it only deletes the line where the `﻿__AUTO_GENERATED_PRINT_VAR__` comment was located. 

Is it possible to detect and delete the entire text object of the debug statement, instead of just the line?

<img width="420" alt="image" src="https://github.com/ThePrimeagen/refactoring.nvim/assets/6158959/f110c5a4-7a29-486e-9443-3f5681fdfecf">
<img width="420" alt="image" src="https://github.com/ThePrimeagen/refactoring.nvim/assets/6158959/21fa42bc-01a5-4fa9-834e-7aec240d4341">

**Comment by TheLeoP** [comment]
Currently, the inserted comment is used to check which lines should be deleted. My firsth thougth is that a comment could be inserted before and after the debug print in order to detect the full range to be deleted in cases like this. Would this work with prettier?

**Comment by rafaelderolez** [comment]
This is what it looks like with my prettier config if I prepend a comment. Doesn't look pretty but it should allow you to detect which range of lines to delete.

```javascript
  /* __START_AUTO_GENERATED_PRINT_VAR__ */ console.log(
    'NEXT_PUBLIC_RESULTS_QUERY_MAX_ATTEMPTS:',
    env.NEXT_PUBLIC_RESULTS_QUERY_MAX_ATTEMPTS
  ); // __END_AUTO_GENERATED_PRINT_VAR__
```

I don't know if this is possible at all, but could you do some sort of upwards-traversing-lookup that detects the beginning of `console.log` (instead of having to prepend a comment)?

**Comment by jackblackevo** [comment]
I have disabled the ESLint and Prettier rules to prevent lint errors, warnings, and formatting. The settings are as follows:

```lua
{
  printf_statements = {
    javascript = {
      'console.log("%s"); /* eslint-disable-line no-console, prettier/prettier */'
    },
    typescript = {
      'console.log("%s"); /* eslint-disable-line no-console, prettier/prettier */'
    },
    typescriptreact = {
      'console.log("%s"); /* eslint-disable-line no-console, prettier/prettier */'
    }
  },
  print_var_statements = {
    javascript = {
      'console.log("%s %%s", %s); /* eslint-disable-line no-console, prettier/prettier */'
    },
    typescript = {
      'console.log("%s %%s", %s); /* eslint-disable-line no-console, prettier/prettier */'
    },
    typescriptreact = {
      'console.log("%s %%s", %s); /* eslint-disable-line no-console, prettier/prettier */'
    }
  }
}
```

I hope this helps. :-)

**Comment by rafaelderolez** [comment]
Not bad! Although this only works if prettier is configured using eslint.

**Comment by TheLeoP** [comment]
@rafaelderolez  #393 should close this. I tried the approach of searching upwards for the print statement, but the fact that the plugin supports multiple languages, custom print statements and i'ts imposible to know where the formatter may split the lines made this option to complex. Instead I used the comment aproach

**Comment by rafaelderolez** [comment]
@TheLeoP alright cool I'll give it a shot when it's merged! Thanks ✌️
