### ISSUE TITLE
Extract function from print with variable in Python3 causing `index out of range`.

### ISSUE THREAD

**Issue by choikangjae** [ThePrimeagen/refactoring.nvim#390]
I have been using this plugin just a couple of hours, so if it is not a bug sorry to bother.

I am using `Python 3.11`.

### Description
When I tried to extract functions contains `print()` with variables in it, it caused `index out of range` error.

```
print(f"var1 = {var1}, var2 = {var2}") => caused error
print("var1 = " + var1 + "var2 = " + var2) => error either
print("Just String") => No error
```

I extracted other lines first and cut and pasted `print()` manually it worked without problems.

### Error messages

```
E5108: Error executing lua ...e/pack/lazy/opt/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine faile
d with this message: ...e/pack/lazy/opt/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...ack/lazy/opt/
refactoring.nvim/lua/refactoring/region.lua:191: index out of range
stack traceback:
        [C]: in function 'error'
        ...e/pack/lazy/opt/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
        ...e/pack/lazy/opt/plenary.nvim/lua/plenary/async/async.lua:45: in function 'on_choice'
        /usr/share/nvim/runtime/lua/vim/ui.lua:54: in function 'select'
        ...pt/refactoring.nvim/lua/refactoring/get_select_input.lua:5: in function 'returned_function'
        ...e/pack/lazy/opt/plenary.nvim/lua/plenary/async/async.lua:31: in function 'callback_or_next'
        ...e/pack/lazy/opt/plenary.nvim/lua/plenary/async/async.lua:45: in function 'step'
        ...e/pack/lazy/opt/plenary.nvim/lua/plenary/async/async.lua:48: in function 'execute'
        ...e/pack/lazy/opt/plenary.nvim/lua/plenary/async/async.lua:108: in function 'run'
        .../pack/lazy/opt/refactoring.nvim/lua/refactoring/init.lua:37: in function 'select_refactor'
        [string ":lua"]:1: in main chunk
```

**Comment by TheLeoP** [comment]
Could you provide the following?
- The full code you encountered the error with
- What part of the code you visually selected
- The exact refactoring command you used (I'm assuming that you used `require('refactoring').refactor('Extract Function')`, but just to be sure)

**Comment by choikangjae** [comment]
- The full code you encountered the error with

    I skipped the full code bc the error was triggered even when I tried to refactor only the `print()` with variables line solely.
Anyway, here it is the code in the context. I simplified the code.
    ```
    import configparser
    image_info = configparser.ConfigParser()

    for loop:
        doing another things..

        image_info[image_hash] = {}
        image_info[image_hash]['path'] = image_rel_path
        image_info[image_hash]['url'] = url
        image_info.write(open(IMAGE_INFO_PATH, 'w'))
        print(f"Image is saved. image = {image_rel_path} url = {url}") <--- error here
    ```
- What part of the code you visually selected
    ```
        {Visual Mode Starts Here} image_info[image_hash] = {}
        image_info[image_hash]['path'] = image_rel_path
        image_info[image_hash]['url'] = url
        image_info.write(open(IMAGE_INFO_PATH, 'w'))
        print(f"Image is saved. image = {image_rel_path} url = {url}") {Visual Mode Ends Here} 
    ```
    But as I said, only the `print(f"Image is saved. image = {image_rel_path} url = {url}")` triggered the error. None of the code above the print line mattered. (I tested.)

- The exact refactoring command you used (I'm assuming that you used require('refactoring').refactor('Extract Function'), but just to be sure)
    That is the one I certainly forgotten.
    - `:lua require('refactoring').select_refactor()<CR>`
    - Choose `2: Extract Function` from the prompt.
    - Enter `Extract Function Name` to `abc` or whatever.
    - I got the error. (Skipped the msg still it is the same as the issue.)

    I tried `:lua require('refactoring').refactor('Extract Function')` and it caused exactly same error so I guess your guess is correct.

And I am using `Lazy` package manager with `LunarVim`. If you need to know anything more than this, please leave me a comment.

**Comment by TheLeoP** [comment]
I'm unable to reproduce your issue. My 2 guesses of why are:

- Lunarvim ships an older version of nvim-treesitter which causes the problem
- Your original string inside of `print(f"...")` contains some multibyte character that your example does not contain (This guess comes fromt he fact that the error happens on a line that should deal with multibyte strings, but I can't confirm it)

**Comment by choikangjae** [comment]
> Your original string inside of print(f"...") contains some multibyte character that your example does not contain...

You are just right! It caused by the multibyte string (Korean). The original string was like this:
```
print(f"이미지가 서버에 저장되었습니다. image = {image_rel_path} url = {url}")
```
It caused error but after I change it to this:

```
print(f"image = {image_rel_path} url = {url}")
```
There are no errors.

I have never expected Korean was the problem, sorry for simplification.

So after all of that, I cannot use CJK when I refactoring with this plugin? Or maybe it is the problem with Python? I am not really sure.

**Comment by TheLeoP** [comment]
> You are just right! It caused by the multibyte string (Korean)

Yay. Now I can reproduce the issue. I'll look into it.

> I have never expected Korean was the problem, sorry for simplification.

Don't worry. Lua strings are just arrays of bytes, that's why multibyte strings can cause this kind of issues.

**Comment by TheLeoP** [comment]
I have solved this issue :D (I think). Could you try [this branch](https://github.com/theleop/refactoring.nvim/tree/fix_390) to confirm that this is working now?

**Comment by choikangjae** [comment]
> I have solved this issue :D (I think). Could you try [this branch](https://github.com/theleop/refactoring.nvim/tree/fix_390) to confirm that this is working now?

I confirmed fixed branch is working perfectly for Korean, Chinese and Japanese when I `extract function`.

Thanks for your help!
