### ISSUE TITLE
[Question] would a refactor for using query files make sense?

### ISSUE THREAD

**Issue by TheLeoP** [ThePrimeagen/refactoring.nvim#395]
Would a refactor for defining queries on query files (something like `refactor.scm`) instead defining them on `treesitter/lang/lang.lua` make sense? In this way, all queries could have a uniform interface.

Also, since the `locals` module of `nvim-treesitter` may be removed in the future (or separated into it's own plugin), we could include part of that module into this plugin and extend it to our needs. Currently, this plugin already uses the `locals` module of nvim-treesitter for `123`, tha't why I thought it could make sense to include it.

**Comment by pranavrao145** [comment]
Hey @TheLeoP, back in the olden days we actually used to use `scm` files for housing queries. We decided to move to inline query nodes for better error handling as well as the ability to query capabilities per language.

As for the locals, I think including their code this plugin and extending it is a good idea.
