### ISSUE TITLE
In-lining variable with C++ braced initialization is broken

### ISSUE THREAD

**Issue by thetic** [ThePrimeagen/refactoring.nvim#427]
Given:

```c++
int x{1};
int y = x + 1;
```

In-lining `x` on the second line results in

```c++
int y = {1} + 1;
```

which is invalid. The braces should not be included.

**Comment by TheLeoP** [comment]
Can you check if #430 solves this? I don't use CPP myself and the CPP treesitter parsers does not expose a single node that contains all the information inside the braced initialization (it has named nodes for things like numbers and anonymous nodes for commas and the brackets themselves).

**Comment by thetic** [comment]
This appears to work as expected. Thank you!
