### ISSUE TITLE
FR: notification how many changes occurred when extracting/inlining variable

### ISSUE THREAD

**Issue by chrisgrieser** [ThePrimeagen/refactoring.nvim#428]
I think it would be nice for inlining/extracting variables to (optionally) have a notification how many occurrences were affected. It's a nice confirmation that the refactoring actually did what you intended to do, as it is possible to select a variable at the wrong scope and thus accidentally changing the wrong variable. A simple notification could already put a stopgap to that.

[inc-rename.nvim](https://github.com/smjonas/inc-rename.nvim) does something like that already, and I found it quite useful.

![Pasted image 2024-01-04 at 19 10 02@2x](https://github.com/ThePrimeagen/refactoring.nvim/assets/73286100/94da60f5-da30-4e8c-b972-54a4d111392b)

**Comment by TheLeoP** [comment]
Is something like #431 what you are looking for?

**Comment by chrisgrieser** [comment]
yep, that's exactly it!

Minor nit: I personally would prefer it to be `vim.notify("Inlined x occurences", vim.log.levels.INFO, { title = "Refactor" })` instead of prefixing `[Refactor]` to the message. This makes it look better for users of [nvim-notify](https://github.com/rcarriga/nvim-notify). But as I said, only personal aesthetic preference. Would work either.
