### ISSUE TITLE
Feature Request: chop-down a.k.a. put arguments on separate lines

### ISSUE THREAD

**Issue by tubignat** [ThePrimeagen/refactoring.nvim#437]
There's a refactoring in IntelliJ-based IDEs that I quite like which allows you to put a list of arguments in a function signature / items in a struct / html attributes on their own separate lines.

Examples:

```
useEffect(() => alert('123'), [])

--->

useEffect(
    () => alert('123'),
    [],
)
```

```
<Title className="123" prop1="234" abc={bcd} />

--->

<Title
    className="123"
    prop1="234"
    abc={bcd}
/>
```

I'm not sure if it's in the scope of this project, but that would be very useful since it's not easily achievable with pure Vim. If it is in scope I would be happy to work on the implementation myself.

**Comment by TheLeoP** [comment]
This sounds like [treesj](https://github.com/Wansmer/treesj) (using treesitter) or [mini.join](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-splitjoin.md) (using lua patterns)

**Comment by tubignat** [comment]
Yep, that's exactly it, thank you for the great suggestion. Closing the issue then
