### ISSUE TITLE
Extracted function goes on top of imports

### ISSUE THREAD

**Issue by eslamallamAdri** [ThePrimeagen/refactoring.nvim#438]
I have this demo python script:

![image](https://github.com/ThePrimeagen/refactoring.nvim/assets/117001147/6febecc2-2eaf-4bfe-b873-c11b320bee06)

When I use the extract function option on the section indicated by the two comments, the new function appears before the imports: 

![image](https://github.com/ThePrimeagen/refactoring.nvim/assets/117001147/179c3a37-1464-4f1a-884e-b31f46533b6c)

This isn't a big deal for such a small file but when working with big files with lots of imports it can get quite inconvenient. Is this by design or can it be fixed?

**Comment by TheLeoP** [comment]
> Is this by design or can it be fixed?

This is a bug and should be fixed
