### ISSUE TITLE
[Feature Request] `Extract To File` automatically create the directory if it does not exist.

### ISSUE THREAD

**Issue by singlexyz** [ThePrimeagen/refactoring.nvim#439]

**Comment by TheLeoP** [comment]
Currently we aren't automatically saving the new file when extracted, could you check if saving the file with `:w ++p` works for your use case? If not, what would this feature look like for you?

**Comment by singlexyz** [comment]
> Currently we aren't automatically saving the new file when extracted, could you check if saving the file with `:w ++p` works for your use case? If not, what would this feature look like for you?

Yeah, `:w ++p` can be used, but this requires manually inputting the full path.
And using `Extract to File`, it will complete the path of the current file.

e.g. file `app/ui/page.jsx` would by default have the path `app/ui`.
<img width="494" alt="image" src="https://github.com/ThePrimeagen/refactoring.nvim/assets/4456413/c62d810d-09bf-42e3-8921-cb38c79d48cb">

**Comment by TheLeoP** [comment]
I'm not sure I'm understanding you. You can delete the default relative path provided and use any path to extract to file.

> Yeah, :w ++p can be used, but this requires manually inputting the full path.

What would be an alternative workflow that won't require manually inputting the full path?
