### ISSUE TITLE
[ERROR] Better error handling for unsupported languages (LSP)

### ISSUE THREAD

**Issue by websorz** [ThePrimeagen/refactoring.nvim#449]
Trying to extract blocks in sveltekit using the svelte LSP throws the following exception:

`Error executing Lua callback: ...e/pack/lazy/opt/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...factoring.nvim/lua/refactoring/treesitter/treesitter.lua:106: scope_names setting is empty in treesit
ter for this language
stack traceback:
        [C]: in function 'error'
        ...e/pack/lazy/opt/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
        ...e/pack/lazy/opt/plenary.nvim/lua/plenary/async/async.lua:45: in function 'step'
        ...e/pack/lazy/opt/plenary.nvim/lua/plenary/async/async.lua:48: in function 'execute'
        ...e/pack/lazy/opt/plenary.nvim/lua/plenary/async/async.lua:118: in function <...e/pack/lazy/opt/plenary.nvim/lua/plenary/async/async.lua:117>
        ...y/opt/refactoring.nvim/lua/refactoring/pipeline/init.lua:77: in function 'run'
        ...zy/opt/refactoring.nvim/lua/refactoring/refactor/106.lua:572: in function <...zy/opt/refactoring.nvim/lua/refactoring/refactor/106.lua:555>
        .../pack/lazy/opt/refactoring.nvim/lua/refactoring/init.lua:29: in function 'refactor'
        ...ck/lazy/opt/refactoring.nvim/lua/refactoring/command.lua:76: in function <...ck/lazy/opt/refactoring.nvim/lua/refactoring/command.lua:60>
`

I'd like better error handling that just tells me that the LSP is unsupported, otherwise it just seems like the plugin doesn't work properly.

**Comment by TheLeoP** [comment]
> using the svelte LSP 

This plugin has nothing to do with LSP

> I'd like better error handling

That makes sense, I'll look into it
