### ISSUE TITLE
[Bug] 106: Strange newlines, results, and placement when extracting a function

### ISSUE THREAD

**Issue by ColinKennedy** [ThePrimeagen/refactoring.nvim#452]
Select the lines

```python
blah = "something"
do_thing(blah)
```

## Before

```python
class Foo(_Base):
    """Some stuff here."""

    def __init__(self) -> None:
        """More things."""
        blah = "something"
        do_thing(blah)

        super().__init__(another=10, stuff=8, blah=blah)
```

## Expected
```python
class Foo(_Base):
    """Some stuff here."""

    def __init__(self) -> None:
        """More things."""
        blah = self.new_function()

        super().__init__(another=10, stuff=8, blah=blah)

    def new_function(self) -> str:
        blah = "something"
        do_thing(blah)

        return blah
```

## Actual
```python
class Foo(_Base):
    """Some stuff here."""

    def new_function(self, ) -> None:
        blah = "something"
        do_thing(blah)
        return blah



    def __init__(self) -> None:
        """More things."""
        blah = self.new_function()


        super().__init__(another=10, stuff=8, blah=blah)
```

- The space between the functions is very wide for some reasons
- new_function is placed above `__init__`. While not "wrong", it is pretty atypical of Python code. The `__init__` is usually the first method
- `def new_function(self, )` gets a trailing `, )` when `def new_function(self)` was expected
- lots of newlines were left over where `blah = self.new_function()` was placed. Expected a maximum of one newline because that is what the original function had
- The refactor saw `blah` but didn't take into account its typehint and wrote `def new_function(self, ) -> None:` rather than `def new_function(self, ) -> str:`

On a positive note - I was surprised and impressed that the refactor tool noticed the use of `blah` and made sure the function returns it. Though with the formatting problems mentioned above, a number of edits would still be needed a number of manual tweaks to get things to work closer to expectations.

**Comment by TheLeoP** [comment]
> The space between the functions is very wide for some reasons

This is simply how the template for python functions and methods is defined. This could be changed if deemed necessary.

https://github.com/ThePrimeagen/refactoring.nvim/blob/d2786877c91aa409c824f27b4ce8a9f560dda60a/lua/refactoring/code_generation/langs/python.lua#L22-L26

https://github.com/ThePrimeagen/refactoring.nvim/blob/d2786877c91aa409c824f27b4ce8a9f560dda60a/lua/refactoring/code_generation/langs/python.lua#L44-L48

> new_function is placed above __init__. While not "wrong", it is pretty atypical of Python code. The __init__ is usually the first method

By the default, the plugin puts the extracted function above because some languages need this is in order to call the function correctly.

> def new_function(self, ) gets a trailing , ) when def new_function(self) was expected

This is an error on the aforementioned python method template. I'm gonna fix it, thanks c:

> lots of newlines were left over where blah = self.new_function() was placed. Expected a maximum of one newline because that is what the original function had

Newlines aren't being inserted. When extracting the text, the plugin isn't deleting the newlines that were already there. Currently, this is on purpose, but could also be changed if deemed desirable.

> The refactor saw blah but didn't take into account its typehint and wrote def new_function(self, ) -> None: rather than def new_function(self, ) -> str:

Treesitter (which is what this plugin mostly uses) is capable of syntactic analysis, not semantical analysis. In this case, this roughly translates to "if it's not written in the file, we can't see it". If `blah` was an argument with a type hint (the only case we currently handle IIRC), it would be present in the extracted function.

I guess we could add language specific type inference to the plugin (in this case, checking what is at the right hand side of the `blah` assignment and trying to infer it's type). A PR would be welcomed c:


> On a positive note - I was surprised and impressed that the refactor tool noticed the use of blah and made sure the function returns it. Though with the formatting problems mentioned above, a number of edits would still be needed a number of manual tweaks to get things to work closer to expectations.

Thanks c: (even though I didn't implement the feature)

**Comment by ColinKennedy** [comment]
> This is simply how the template for python functions and methods is defined. This could be changed if deemed necessary.

[PEP8](https://peps.python.org/pep-0008) recommends 2 empty lines between functions and 1 empty line between methods (class functions). So I'd imagine a template improvement would be to set add 1 newline + add an extra newline if the cursor is not directly within a parent class. That'd handle all cases. for `106`, at least.

> If blah was an argument with a type hint (the only case we currently handle IIRC), it would be present in the extracted function.

I'm not sure if this is what you meant but changing `blah = "something"` to `blah: str = "something"` doesn't result in 

```python
    def some_function(self, ) -> str:
        blah = "something"
        do_thing(blah)
        return blah
```

it still posts as

```python
    def some_function(self, ) -> None:
        blah: str = "something"
        do_thing(blah)
        return blah
```

Since it's written explicitly as `blah: str`, there is no inference needed but the created function doesn't post the return type.

**Comment by ColinKennedy** [comment]
> Newlines aren't being inserted. When extracting the text, the plugin isn't deleting the newlines that were already there. Currently, this is on purpose, but could also be changed if deemed desirable.

That would definitely be a great configuration option to opt-in to. It could just be my opinion when I delete a line, I typically `dd` it rather than `^d$` it (which would leave empty space). So when I tried out removing lines via this plugin I expected behavior closer to `dd`. Maybe that's just my assumption.

**Comment by TheLeoP** [comment]
> I'm not sure if this is what you meant but changing blah = "something" to blah: str = "something" doesn't result in

I was thinking of somethink like

```python
class Foo(_Base):
    """Some stuff here."""

    def __init__(self, blah: str) -> None:
        """More things."""
        blah = "something"
        do_thing(blah)

        super().__init__(another=10, stuff=8, blah=blah)
```
but this results in

```python
class Foo(_Base):
    """Some stuff here."""

    def foo(self, blah: str) -> None:
        blah = "something"
        do_thing(blah)
        return blah



    def __init__(self, blah: str) -> None:
        """More things."""
        blah = self.foo(blah)


        super().__init__(another=10, stuff=8, blah=blah)
```

It looks like currently we are only inferring the types of arguments

https://github.com/ThePrimeagen/refactoring.nvim/blob/d2786877c91aa409c824f27b4ce8a9f560dda60a/lua/refactoring/refactor/106.lua#L205-L208

and optionally letting users enable a prompt to select the return type of the function

https://github.com/ThePrimeagen/refactoring.nvim/blob/d2786877c91aa409c824f27b4ce8a9f560dda60a/lua/refactoring/refactor/106.lua#L210-L215

**Comment by TheLeoP** [comment]
> [PEP8](https://peps.python.org/pep-0008) recommends 2 empty lines between functions and 1 empty line between methods (class functions). So I'd imagine a template improvement would be to set add 1 newline + add an extra newline if the cursor is not within a parent class. That'd handle all cases. for `106`, at least.

I think we could safely leave one newline on functions and two newlines on methods.

**Comment by TheLeoP** [comment]
@ColinKennedy  could you check #454? I still need to adress the deletion of empty lines when extracting, but that's not python specific
