### ISSUE TITLE
Feature request: skip Enter in refactors menu if there are fewer than 10 options

### ISSUE THREAD

**Issue by GalLalouche** [ThePrimeagen/refactoring.nvim#453]
It would be nice if I could save a button press (50% of all button presses in the menu!) in the refactors menu, if it would just accept the input number in the case where there are fewer than 10 options and not wait for Enter. (Or if anyone could suggest a workaround, that'd be great too!)

![image](https://github.com/ThePrimeagen/refactoring.nvim/assets/6412249/e511742c-fd89-46e5-9903-bc1695014c7c)

**Comment by TheLeoP** [comment]
We are using `vim.ui.select` (`:h vim.ui.select`) under the hood, which by default uses `vim.fn.select` (`:h select`), this is the interface you are seeing. `vim.ui.select` is designed to be able to be overriden by plugins (I'm using a `select` function exposed by fzf-lua, for example) and users
