### ISSUE TITLE
Extracting to Function in jsx files

### ISSUE THREAD

**Issue by Redoxahmii** [ThePrimeagen/refactoring.nvim#459]
`  ...zy/refactoring.nvim/lua/refactoring/treesitter/nodes.lua:88: Invalid query: '((formal_parameters (required_ 
 _parameter (identifier) @tmp_capture)))' 
 error: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 1:22. Invalid node type "requ 
 uired_parameter": 
 ((formal_parameters (required_parameter (identifier) @tmp_capture))) 
 ^ `
 
 Gives this error whenever using it with `.jsx` files.

**Comment by TheLeoP** [comment]
Could you provide a minimal snippet of code to reproduce the error?

**Comment by Redoxahmii** [comment]
Maybe this would make it more clearer.
It works fine if i Extract to Variable but this only happens when using with Function.
I am using LazyVim integration of this.

https://github.com/ThePrimeagen/refactoring.nvim/assets/13983258/ac47745e-36c4-43e4-8e80-bd6bd319e650

**Comment by TheLeoP** [comment]
Does #460 fix the issue?

**Comment by Redoxahmii** [comment]
No it gives this error now.

`  ...factoring.nvim/lua/refactoring/treesitter/treesitter.lua:106: ident_with_type setting is empty in treesitte 
 er for this language `.

![t_2024_06_22_09_55](https://github.com/ThePrimeagen/refactoring.nvim/assets/13983258/8b616ab6-fb4f-45a6-bebc-8d26a7e1c569)

**Comment by TheLeoP** [comment]
And now?

**Comment by Redoxahmii** [comment]
Yes it works now.
Is inlining not supported for `jsx` and `tsx`?
Because when i extract to a Function in these files it does not seem to inline it there but the Extract Variable does inline properly.
Unfortunately i cannot use Extract Variable from my case as it is preferred to be a Function in React.

**Comment by TheLeoP** [comment]
Inline function probably isn't working. Only support for Go, lua, and C was added to inline function (other languages would need to add the required captures). Anyhow, only really simple functions can be inlined by this pluign (e.g. if it has multiple returns, it won't be inlined)

**Comment by Redoxahmii** [comment]
I might have not phrased it correctly.

- Using `Extract Variable` it seems to remove and replace text there with what we use as the Var Name but that does not happen similarly for Function.

https://github.com/ThePrimeagen/refactoring.nvim/assets/13983258/2449ef7b-299f-46d9-99f6-f47eb224d763

**Comment by TheLeoP** [comment]
Because of how extract variable works, you need to select on **visual line** mode what you want to be extracted

**Comment by Redoxahmii** [comment]
That does not seem to work even when using with with Visual Line mode:
Demonstrated here :


https://github.com/ThePrimeagen/refactoring.nvim/assets/13983258/17f58f83-4fff-448f-88d9-04e64c6a665a

**Comment by Redoxahmii** [comment]
@TheLeoP i found this plugin that used to work using the similar concept of using treesitter parsers but this is not maintained anymore and seems to be a dead repo but can help in providing a guiding way.

[react-extract.nvim](https://github.com/napmn/react-extract.nvim)

Having it work properly like this would be a life saver as the code actions provided by the lsp server also do not have the option to create new files and save in that file properly even tho i am using `vtsls` just for better code actions so this would be really helpful.
