### ISSUE TITLE
Unexpected behaviour in python

### ISSUE THREAD

**Issue by AckslD** [ThePrimeagen/refactoring.nvim#46]
Awesome work on this plugin! Just reporting some strange behaviour in python.

I tried this out on the following file:
```python
def main():
    """Some docs

    Args:
    """
    msg = 'hello'
    print(msg)
```
with the two last lines selected and after extracting a function I ended up with
```python

def tmp(msg):
        print(msg)
    return fill_me


def main():
    """Some docs

    Args:
    """
    msg = 'hello'

fill_me = tmp(msg)
```

**Comment by AckslD** [comment]
Maybe duplicate of #44?

**Comment by ThePrimeagen** [comment]
My guess is that we don't have a formatter for python yet.

I also haven't worked the config to be overridable yet.  This "should" fix the issue.  But let me play around with this shortly.  (I didn't add the python support and I was scared too due to whitespace being meaningful :))

**Comment by AckslD** [comment]
Cool! Yeah indeed whitespace in python could make it tricky (for example the above is not correct even up to formatting). Hopefully leveraging treesitter/lsp can make this possible :)

**Comment by AckslD** [comment]
Just tried this again and seems to be fixed :)
