### ISSUE TITLE
[Python] Extract var unable to determine its containing statement within the block scope

### ISSUE THREAD

**Issue by gbelouze** [ThePrimeagen/refactoring.nvim#461]
Hi and thanks for this great plugin !

I'm just following the package demands here :

- I have this Python code
```python
with open(writer_log_path / "config.json", "w+") as config_file:
    config_file.write(jsons.dumps(config))
log.info(f"Dumped config at {config_path}")
```

- Having `writer_log_path / "config.json"` highlighted, I hit `<Space>rv` which is mapped to
```lua
function()
  require("refactoring").refactor("Extract Variable")
end,
"Refactor: Extract [v]ariable",
mode = "x",
```

- This raises 
```
Extract var unable to determine its containing statement within the block scope, please post issue with exact highlight + code!  Thanks
```

I was expecting it to generate
```python
var_name = writer_log_path / "config.json"
with open(var_name, "w+") as config_file:
    config_file.write(jsons.dumps(config))
log.info(f"Dumped config at {config_path}")
```
Seems to be an issue with the context manager statement `with` ?

(the name is : I'm not sure if this is a package issue or a me issue I'm just following what I'm told-gen)

**Comment by TheLeoP** [comment]
Thanks! This is indeed an error coming from this plugin. #462 should fix it, but I'll fix the indentation on a different PR
