### ISSUE TITLE
Feature Request: Extract function in React and remove the lines with <Foo />

### ISSUE THREAD

**Issue by Redoxahmii** [ThePrimeagen/refactoring.nvim#474]
Currently the extract to function works very good but the issue is that it does not remove the lines that were extracted from there.
This works well if you are extracting to a variable and leaves behind `{Foo}` whereas extract to function does not do that.
i would'nt consider the `{Foo}` syntax to be correct so in Extract Function it should remove those lines and leave `<Foo />` behind.

**Comment by TheLeoP** [comment]
Could you provide a code example of what you mean? The starting code, the code after extracting to function by this plugin and what you expect the code to be after extracting it to a function

**Comment by Redoxahmii** [comment]
- The First screenshot shows what i am extracting :

![1st](https://github.com/user-attachments/assets/c04c3746-9f34-400c-8d94-b103bf43f482)

- 2nd Screenshot shows that it does create a function but does not remove the selection from there :

![2nd](https://github.com/user-attachments/assets/12c1a812-15b5-43e2-a45c-813a2cf8f06a)

- This shows what it should leave behind if we remain in the syntax of React :

![3rd](https://github.com/user-attachments/assets/5e46c542-e7ff-40fa-bb99-e5665daac4c9)

- This shows what it does when you instead use `Extract to Variable`. This not only replaces it there but also does for the same occurrences in that buffer which could be troublesome. It should only do it for what we are using for but i would leave this upto you how this should work but i think it should not replace all occurrences:

![4th](https://github.com/user-attachments/assets/fca6934c-b81a-48c3-9512-d27d496e66fe)

- In this last you can see why this could be troublesome for all occurrences as it also replaces the same occurrences that are ingested inside some other layout :

![5th](https://github.com/user-attachments/assets/ab9a0012-8f07-4912-9c89-e619ef2f60b7)


If i have the following without any wrapping element :
```jsx
<Text variant="h1" className="mb-6">
        JWT Authentication
      </Text>
```
But ingested inside some wrapping element such as :
```jsx
<Text className="mb-4">
        <Text variant="h1" className="mb-6">
          JWT Authentication
        </Text>
        we&apos;re able to authenticate users before they hit your app.
      </Text>
```
By replacing all occurrences it could result in issues. The last screenshot should make this more clear.

**Comment by TheLeoP** [comment]
Does #476 fix this for you?

**Comment by TheLeoP** [comment]
> This not only replaces it there but also does for the same occurrences in that buffer

This is how extract variable works for all languages (being the oposite of inline variable)

> In this last you can see why this could be troublesome for all occurrences as it also replaces the same occurrences that are ingested inside some other layout

I don't fully understand why this is a problem. Is this a syntactic error? Are the other ocurrences not supposed to have the same value as the extracted variable? I think that either I'm not understanding the problem or you may be not understanding the purpose of the extract variable refactor

**Comment by Redoxahmii** [comment]
From a language perspective it is understandable what you're saying but from the library perspective it could be annoying as something might be similar but serve different purposes with the progression of the code which as i said already is not a huge issue and would occur very rarely.

This is purely a **React**  and **UI** issue as UIs could have exact same things but one could be inside a component which we are creating with the Refactor plugin and the other would have to a be a separate entity from that although they are exactly same because **React** and **UI** so no worries about that.

If i am writing functions above that do not include the **jsx** aspect of having `html` inside it then it is the best option to replace all occurrences  for any programming language.

 It was just an addition to it i wanted to add.

**Comment by Redoxahmii** [comment]
Yes #476 fixes it thank you for your time. 
Closing this issue.

**Comment by Redoxahmii** [comment]
Sorry for reopening this but i found an issue with this where it is not putting the variables as props for the function.

- In this i extract a Function which has 2 variables being used inside it which is `Count` and `setCount`:

![t_2024_07_27_02_58](https://github.com/user-attachments/assets/646b4f46-dd92-4d32-8644-8f049e8d5e6b)

- As the function exists outside of the other function those variables have to be passed as props to them it creates this function as you can see :

![t_2024_07_27_02_59](https://github.com/user-attachments/assets/3d405324-901c-4dff-bbc7-172a7f6a29d8)

- The end result should look like this instead where the variables are passed to the component and also referenced in the extracted function as props :

![t_2024_07_27_03_01](https://github.com/user-attachments/assets/ed6c81e7-4e8e-4b31-bf7a-dc5b6bd230ac)

You can see those variables are not only being passed to the component with ` <Foo count={count} setCount={setCount} />` but are also included in the props above as :
```jsx
function Foo({ count, setCount }) {
  return (
    <>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.jsx</code> and save to test HMR
        </p>
      </div>
    </>
  );
}
```
If this is out of the scope of the plugin i will close this again.
Thank you for your work and time.

**Comment by Redoxahmii** [comment]
I have not used this plugin too much but this seemed to be working before for as far as i can remember.

**Comment by TheLeoP** [comment]
> Sorry for reopening this but

Don't worry.

Could you check if #477 fixes this?

**Comment by Redoxahmii** [comment]
Thank you for the quick responses. 
This fixes the issue when using `Extract to Function` but if i use `Extract Function to File` the behavior is same as before.

One more thing is if i am extracting the function to a file should it have an auto import for that file above cause i am not entirely sure if that is something this plugin supports.

Currently there is no auto import.

This most probably might be out of the scope of the plugin because then every function extracted to a file would need `export default` or `export` appended to the function so the import actually works when added on the top.

Having these different behaviors for these would make it perfect as extracted code to a file is most likely to be then called on the top and used and is the higher probability case.

This wouldn't be the same for a `Extract Function` and for a `Extract function to a file`.

**Comment by TheLeoP** [comment]
> One more thing is if i am extracting the function to a file should it have an auto import for that file above cause i am not entirely sure if that is something this plugin supports.

This is out of scope for this plugin

> This fixes the issue when using Extract to Function but if i use Extract Function to File the behavior is same as before.

This turned out to be a problem with extract to file in general, thanks for the report :D. I'll fix it in a different PR
