### ISSUE TITLE
Add ability to add support to new language

### ISSUE THREAD

**Issue by fabiomcosta** [ThePrimeagen/refactoring.nvim#475]
It would be nice if I could quickly add support to a new language without having to create a pull request, document everything etc etc

Is this already possible today? If it is it's not documented, so that would be the actionable item here.

Thank you for the plugin! I actually was thinking about how much time I spend writting the same code to log the value of a varaible and this addresses that :)

**Comment by TheLeoP** [comment]
Currently, isn't not possible for an end user to add support for a new language inside of this plugin's configuration.

I don't see it as a compeling use case, I think that any new language support would be better as a PR so any user of the plugin can benefit from it
