### ISSUE TITLE
Find similarly structured code

### ISSUE THREAD

**Issue by adgai19** [ThePrimeagen/refactoring.nvim#51]
This could be helpful while finding code that is repeated for function extraction. The result could be thrown inside a qf list. I think the necessary api is already in.

**Comment by ThePrimeagen** [comment]
I have thought about this a lot.  I may write a stand alone binary for this operation.  Its extremely cpu intensive but could be neat.

**Comment by pranavrao145** [comment]
Closing because I think this is a duplicate of #249.
