### ISSUE TITLE
Thinking of Refactor object.  Should we change it?

### ISSUE THREAD

**Issue by ThePrimeagen** [ThePrimeagen/refactoring.nvim#60]
First thought, what???

Second thought, why??

Ok, follow me.  The pipeline pattern that is emerging is a bit of a implied structure throughout the code and I don't like it.  It makes it hard for any new person to understand where things come from.  What if we strip out the logic and put them into functions that are called within the refactor operations.

example: I also don't mean to rid of all the refactor object, just confine it a bit
```lua
-- Inline var refactor
local definition = lsp_utils.get_definition_under_cursor(refactor.bufnr)
local references = lsp_utils.get_references(definition)
...
```

The only downside I see is error handling.  This can become really annoying.

I don't have a clear idea of where I want to go, I just like the implicit communications that are happening.

Effectively we are a weak decorator pattern.

**Comment by tjdevries** [comment]
As of right now I haven't seen anything in the pipeline pattern that buys you anything new over just calling the functions in a row or appending them to a table or some other lua primitive.

**Comment by ThePrimeagen** [comment]
I completely agree. I thought there may be more better good, but instead it sucks.

Better to just have some tables in my book.

**Comment by pranavrao145** [comment]
For now I'm just going to close this issue due to inactivity, but in case we want to reopen later on to reconsider this we can do that as well.
