### ISSUE TITLE
Cancel refactor if no name specified

### ISSUE THREAD

**Issue by seblj** [ThePrimeagen/refactoring.nvim#62]
Just want to start of saying that this project is really awesome, and I really look forward to seeing this project grow! I found a bug where the extraction of a function is done even if I want to cancel the input of inputing the function name. See video for an example

https://user-images.githubusercontent.com/5160701/129485702-00ee9f44-e05b-410e-a7b5-02485cb991e6.mov

**Comment by teddylear** [comment]
I can take a look into this.

**Comment by ThePrimeagen** [comment]
CHEERS!  THanks :)
