### ISSUE TITLE
Add official language support

### ISSUE THREAD

**Issue by ThePrimeagen** [ThePrimeagen/refactoring.nvim#69]
I think that we need to add an "official language" support.

I am pretty fine handling the following:

* typescript (I _may_ remember to do javascript too)
* golang
* cpp

(cpp isn't supported currently, but I'll want to support this long run)

Does anyone want to volunteer as the "go to" on the language?

**Comment by teddylear** [comment]
Even though it's difficult (like typescript), I think we want lua to have first class support as it will then make even writing the plugin easier.

**Comment by kubabialy** [comment]
I'll go throught the plugin and fiddle with it for a while and try to make it work with PHP. If that'll work I'm happy to maintain it for that language and perhaps help when available with JS/TS.

**Comment by pranavrao145** [comment]
Closing this issue for now due to inactivity (plus, a lot of languages have since been added, doesn't make much sense anymore).
