### ISSUE TITLE
Indent to same column position when replacing text

### ISSUE THREAD

**Issue by teddylear** [ThePrimeagen/refactoring.nvim#71]
One issue that I've seen with almost all of the languages is when text is replacing other text, it is not going to column where the first node remove was, it's always going to column 0 (or 1 if 1 is the start, I can't remember). From checking the function `vim.lsp.util.apply_text_edits` vs the treesitter node column, I don't know if this is possible but wanted to raise the issue in case I'm missing something. Some formatting will resolve this (like `gofmt` if that gets integrated), but this would resolve the issue for most languages I believe.

**Comment by ThePrimeagen** [comment]
I would LOVE to do this.

I was thinking about creating this during the `refactor` setup phase.  It determines the indent of current line.  Perhaps some simple line stats class dangling off of the `refactor` object (which should turn into a class soon)

**Comment by muchzill4** [comment]
I was thinking about this as well. I don't think we can depend solely on a formatter for a language like python, where whitespace carries meaning. I suppose we'd need to pass the information about the original ident around, so that the output can be _formatted_ accordingly. Also, worth considering situations where you may want to modify ident levels as you extract functions. Consider:

```python
class PrintingCalculator:
    def add_one_and_print(self, x: int) -> int:
        plus_one = x + 1

        print("---")
        print(f"Result: {plus_one}")
        print("---")
``` 

Assuming we'd want to extract all the `print`s, where should it land? 
a) Outside of the class? Need to dedent by one level.
b) Inside the class, but separate method? Need to keep indentation level.

Perhaps I'm missing something, but I'm not sure how this could work w/o keeping hold of the ident level information until the extraction is output. 🤔

**Comment by ThePrimeagen** [comment]
For 106 we would have to do the following:
1. Determine scope of refactor
2. Determine scope's indenting
3. Determine outer scope's indenting
4. Apply constant creation's indenting with scope's indenting level
5. Apply function creation with outer scope's indenting.

Each of these will have to have their own determination for indenting.  We will also have to use vim's tab settings to determine if we are doing 4 white spaces or a tab.  There is a lot to do on this.

**Comment by ThePrimeagen** [comment]
addressing @muchzill4 great points, we will also need to consider pulling functions out as class level vs out side class level.

There is still a lot to be done, and I am certainly not claiming we are close, but I would like to get there!

For part of this we may need to make language specific operations.  You can imagine applying function level protection (private / public / whatever) is going to be a very language specific task.  It will require node traversing at a language level.  Not a huge fan of taht :)

**Comment by teddylear** [comment]
@muchzill4 I was playing around on this with python for adding whitespace to the text during   code generation for 106. The idea I had was for languages where the formatter won't help like you mentioned, but we just always pass in the column of the first node column into code generation. Then let code generation determine if it uses it. Where I got hung up was determining the nodes in the current region to find the first node.

**Comment by ThePrimeagen** [comment]
There is something called indentexpr, this could really help!

**Comment by pranavrao145** [comment]
Given the advances made in indentation in the last year and a bit, I'll close this issue for now - we can open issues for specific indentation cases later on if need be.
