### ISSUE TITLE
Support for C/C++ refactoring

### ISSUE THREAD

**Issue by amirrezasadeqi** [ThePrimeagen/refactoring.nvim#98]
Hi There Primeagen. 

First of all thanks for your nice project. This feature is amazing and I never thought that we can get it on neovim.

watching your work on your youtube channel made me interested in having this feature for C/C++ projects. So I want to know that do you have any plan to extend this plugin for C/C++ ?

If you have not any plan to do this, Can I ask you to give me some hints to learn the procedure of adding C/C++ support?

things that I have done to do this:
 
I had not any experience with lua, but to do this I watched some tutorials on it. after that I reviewed some of your codes (`region.lua` , `utils.lua`, `query.lua` and some more) to learn how you implemented it. I think I understood some part of your code well but still there are some parts that look wierd to me. 

sincerely

Amir Reza Sadeghi

**Comment by ThePrimeagen** [comment]
So yeah!

I am going to do this actually pretty soon myself.  I work on it for my job so I'll be supporting this within the next few weeks.

**Comment by ThePrimeagen** [comment]
Also, if you wish to submit a PR i would be glad to review / point you in the right direction

**Comment by amirrezasadeqi** [comment]
That's nice to hear that. I wish you success. 

About submitting a PR, It would be my pleasure to have this opportunity. it shows your kindness that you want to review my code and guide me. Because this is my first project in Lua, I am not very confident about my code quality but I will do my best. I will fork your project and Start to work on that.

and one more thing. where is the best place to ask you question about that weird chunks of code and the structure of your project?

**Comment by ThePrimeagen** [comment]
> it shows your kindness that you want to review my code and guide me
Hopefully I guide you well!  I really appreciate any contribution even if I don't merge it.  I am continually wow'd by people who want to get their hands dirty.  Good for you

> and one more thing. where is the best place to ask you question about that weird chunks of code and the structure of your project?
[Discord](https://discord.gg/3ujcVMe), #refactoring is the name of the channel

**Comment by ThePrimeagen** [comment]
i will start looking at this soon once I get the extraction code all wrapped up.  Then I will start the language support phase.

**Comment by pranavrao145** [comment]
C++ refactoring is done with #166, C should technically work too but format tests need to be written for it to make sure!

**Comment by Midren** [comment]
C++ integration works like a charm. One moment that I have don't understand, why do we need `INSERT_TYPE_HERE`, when `auto` can be used instead ? It is true, that it won't work for C++98, but it is better to change it to a real type only for those who really need it.

**Comment by pranavrao145** [comment]
I don't mind using `auto` instead, but the other problem is that it also won't work for C. So this means we will have to separate the codegen for each of these and (maybe) write new tests.

**Comment by Midren** [comment]
Modern C++ is pretty different from C, so I think it's okay to have different code gens )

**Comment by pranavrao145** [comment]
Fair enough - do you want to make the PR for that @Midren?

**Comment by Midren** [comment]
Never written in Lua, but will try to find a timeslot tomorrow )

**Comment by teddylear** [comment]
I believe with everything added we are good to close this. If this is still a problem let me know if we can reopen it.
